/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Api
 * Smart Disaster Response and Resource Allocation Platform API
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker'
import {
  HttpResponse,
  delay,
  http
} from 'msw'
import type {
  Shelter,
  ShelterRecommendation
} from '../../../api-zod/src/generated'

export const getListSheltersResponseMock = (): Shelter[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({address: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined]), capacity: faker.number.int({min: undefined, max: undefined}), currentOccupancy: faker.number.int({min: undefined, max: undefined}), facilities: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), undefined]), id: faker.number.int({min: undefined, max: undefined}), latitude: faker.number.int({min: undefined, max: undefined}), longitude: faker.number.int({min: undefined, max: undefined}), name: faker.word.sample(), status: faker.helpers.arrayElement(['available','full','closed'] as const)})))

export const getCreateShelterResponseMock = (overrideResponse: Partial< Shelter > = {}): Shelter => ({address: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined]), capacity: faker.number.int({min: undefined, max: undefined}), currentOccupancy: faker.number.int({min: undefined, max: undefined}), facilities: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), undefined]), id: faker.number.int({min: undefined, max: undefined}), latitude: faker.number.int({min: undefined, max: undefined}), longitude: faker.number.int({min: undefined, max: undefined}), name: faker.word.sample(), status: faker.helpers.arrayElement(['available','full','closed'] as const), ...overrideResponse})

export const getUpdateShelterResponseMock = (overrideResponse: Partial< Shelter > = {}): Shelter => ({address: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined]), capacity: faker.number.int({min: undefined, max: undefined}), currentOccupancy: faker.number.int({min: undefined, max: undefined}), facilities: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), undefined]), id: faker.number.int({min: undefined, max: undefined}), latitude: faker.number.int({min: undefined, max: undefined}), longitude: faker.number.int({min: undefined, max: undefined}), name: faker.word.sample(), status: faker.helpers.arrayElement(['available','full','closed'] as const), ...overrideResponse})

export const getRecommendSheltersResponseMock = (): ShelterRecommendation[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({availableCapacity: faker.number.int({min: undefined, max: undefined}), distanceKm: faker.number.int({min: undefined, max: undefined}), estimatedTravelMinutes: faker.number.int({min: undefined, max: undefined}), score: faker.number.int({min: undefined, max: undefined}), shelter: {address: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined]), capacity: faker.number.int({min: undefined, max: undefined}), currentOccupancy: faker.number.int({min: undefined, max: undefined}), facilities: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), undefined]), id: faker.number.int({min: undefined, max: undefined}), latitude: faker.number.int({min: undefined, max: undefined}), longitude: faker.number.int({min: undefined, max: undefined}), name: faker.word.sample(), status: faker.helpers.arrayElement(['available','full','closed'] as const)}})))


export const getListSheltersMockHandler = (overrideResponse?: Shelter[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Shelter[]> | Shelter[])) => {
  return http.get('*/shelters', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getListSheltersResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getCreateShelterMockHandler = (overrideResponse?: Shelter | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Shelter> | Shelter)) => {
  return http.post('*/shelters', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getCreateShelterResponseMock()),
      {
        status: 201,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getUpdateShelterMockHandler = (overrideResponse?: Shelter | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<Shelter> | Shelter)) => {
  return http.patch('*/shelters/:id', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getUpdateShelterResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getDeleteShelterMockHandler = () => {
  return http.delete('*/shelters/:id', async () => {await delay(1000);
    return new HttpResponse(null,
      {
        status: 204,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getRecommendSheltersMockHandler = (overrideResponse?: ShelterRecommendation[] | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ShelterRecommendation[]> | ShelterRecommendation[])) => {
  return http.post('*/shelters/recommend', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getRecommendSheltersResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}
export const getSheltersMock = () => [
  getListSheltersMockHandler(),
  getCreateShelterMockHandler(),
  getUpdateShelterMockHandler(),
  getDeleteShelterMockHandler(),
  getRecommendSheltersMockHandler()
]
