/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Api
 * Smart Disaster Response and Resource Allocation Platform API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import axios from 'axios'
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  Shelter,
  ShelterInput,
  ShelterRecommendRequest,
  ShelterRecommendation,
  ShelterUpdate
} from '../../../api-zod/src/generated'

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;



/**
 * @summary List all shelters
 */
export const listShelters = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Shelter[]>> => {
    
    return axios.get(
      `/shelters`,options
    );
  }


export const getListSheltersQueryKey = () => {
    return [`/shelters`] as const;
    }

    
export const getListSheltersQueryOptions = <TData = Awaited<ReturnType<typeof listShelters>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listShelters>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSheltersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listShelters>>> = ({ signal }) => listShelters({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listShelters>>, TError, TData> & { queryKey: QueryKey }
}

export type ListSheltersQueryResult = NonNullable<Awaited<ReturnType<typeof listShelters>>>
export type ListSheltersQueryError = AxiosError<unknown>

/**
 * @summary List all shelters
 */
export const useListShelters = <TData = Awaited<ReturnType<typeof listShelters>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listShelters>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getListSheltersQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Add a shelter
 */
export const createShelter = (
    shelterInput: ShelterInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Shelter>> => {
    
    return axios.post(
      `/shelters`,
      shelterInput,options
    );
  }



export const getCreateShelterMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createShelter>>, TError,{data: ShelterInput}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createShelter>>, TError,{data: ShelterInput}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createShelter>>, {data: ShelterInput}> = (props) => {
          const {data} = props ?? {};

          return  createShelter(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateShelterMutationResult = NonNullable<Awaited<ReturnType<typeof createShelter>>>
    export type CreateShelterMutationBody = ShelterInput
    export type CreateShelterMutationError = AxiosError<unknown>

    /**
 * @summary Add a shelter
 */
export const useCreateShelter = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createShelter>>, TError,{data: ShelterInput}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof createShelter>>,
        TError,
        {data: ShelterInput},
        TContext
      > => {

      const mutationOptions = getCreateShelterMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Update shelter
 */
export const updateShelter = (
    id: number,
    shelterUpdate: ShelterUpdate, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Shelter>> => {
    
    return axios.patch(
      `/shelters/${id}`,
      shelterUpdate,options
    );
  }



export const getUpdateShelterMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateShelter>>, TError,{id: number;data: ShelterUpdate}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateShelter>>, TError,{id: number;data: ShelterUpdate}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateShelter>>, {id: number;data: ShelterUpdate}> = (props) => {
          const {id,data} = props ?? {};

          return  updateShelter(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateShelterMutationResult = NonNullable<Awaited<ReturnType<typeof updateShelter>>>
    export type UpdateShelterMutationBody = ShelterUpdate
    export type UpdateShelterMutationError = AxiosError<unknown>

    /**
 * @summary Update shelter
 */
export const useUpdateShelter = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateShelter>>, TError,{id: number;data: ShelterUpdate}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof updateShelter>>,
        TError,
        {id: number;data: ShelterUpdate},
        TContext
      > => {

      const mutationOptions = getUpdateShelterMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Delete shelter
 */
export const deleteShelter = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    return axios.delete(
      `/shelters/${id}`,options
    );
  }



export const getDeleteShelterMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteShelter>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteShelter>>, TError,{id: number}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteShelter>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteShelter(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteShelterMutationResult = NonNullable<Awaited<ReturnType<typeof deleteShelter>>>
    
    export type DeleteShelterMutationError = AxiosError<unknown>

    /**
 * @summary Delete shelter
 */
export const useDeleteShelter = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteShelter>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof deleteShelter>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteShelterMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary BFS-based shelter recommendation for incident
 */
export const recommendShelters = (
    shelterRecommendRequest: ShelterRecommendRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ShelterRecommendation[]>> => {
    
    return axios.post(
      `/shelters/recommend`,
      shelterRecommendRequest,options
    );
  }



export const getRecommendSheltersMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof recommendShelters>>, TError,{data: ShelterRecommendRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof recommendShelters>>, TError,{data: ShelterRecommendRequest}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof recommendShelters>>, {data: ShelterRecommendRequest}> = (props) => {
          const {data} = props ?? {};

          return  recommendShelters(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RecommendSheltersMutationResult = NonNullable<Awaited<ReturnType<typeof recommendShelters>>>
    export type RecommendSheltersMutationBody = ShelterRecommendRequest
    export type RecommendSheltersMutationError = AxiosError<unknown>

    /**
 * @summary BFS-based shelter recommendation for incident
 */
export const useRecommendShelters = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof recommendShelters>>, TError,{data: ShelterRecommendRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof recommendShelters>>,
        TError,
        {data: ShelterRecommendRequest},
        TContext
      > => {

      const mutationOptions = getRecommendSheltersMutationOptions(options);

      return useMutation(mutationOptions);
    }
    