/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Api
 * Smart Disaster Response and Resource Allocation Platform API
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker'
import {
  HttpResponse,
  delay,
  http
} from 'msw'
import type {
  ActionPlan,
  AiPrediction,
  ImageAnalysisResult
} from '../../../api-zod/src/generated'

export const getAnalyzeDisasterImageResponseMock = (overrideResponse: Partial< ImageAnalysisResult > = {}): ImageAnalysisResult => ({analysisNotes: faker.word.sample(), confidenceScore: faker.number.int({min: undefined, max: undefined}), damageLevel: faker.helpers.arrayElement(['minimal','moderate','severe','catastrophic'] as const), detectedCategory: faker.helpers.arrayElement(['flood','earthquake','cyclone','fire','landslide','unknown'] as const), estimatedCasualties: faker.number.int({min: undefined, max: undefined}), requiredResources: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), severity: faker.number.int({min: 1, max: 10}), suggestedPriority: faker.helpers.arrayElement(['low','medium','high','critical'] as const), ...overrideResponse})

export const getGetAiActionPlanResponseMock = (overrideResponse: Partial< ActionPlan > = {}): ActionPlan => ({aiNotes: faker.word.sample(), estimatedResponseHours: faker.number.int({min: undefined, max: undefined}), evacuationUrgency: faker.helpers.arrayElement(['low','moderate','high','immediate'] as const), incidentId: faker.number.int({min: undefined, max: undefined}), requiredTeams: faker.number.int({min: undefined, max: undefined}), resourcePlan: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({allocated: faker.number.int({min: undefined, max: undefined}), category: faker.word.sample(), resourceId: faker.number.int({min: undefined, max: undefined}), resourceName: faker.word.sample(), unit: faker.word.sample()})), shelterCapacityNeeded: faker.number.int({min: undefined, max: undefined}), ...overrideResponse})

export const getListAiPredictionsResponseMock = (): AiPrediction[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({confidenceScore: faker.number.int({min: undefined, max: undefined}), createdAt: faker.word.sample(), id: faker.number.int({min: undefined, max: undefined}), incidentId: faker.number.int({min: undefined, max: undefined}), result: faker.word.sample(), type: faker.helpers.arrayElement(['image_analysis','action_plan','severity_prediction'] as const)})))


export const getAnalyzeDisasterImageMockHandler = (overrideResponse?: ImageAnalysisResult | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ImageAnalysisResult> | ImageAnalysisResult)) => {
  return http.post('*/ai/analyze-image', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getAnalyzeDisasterImageResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetAiActionPlanMockHandler = (overrideResponse?: ActionPlan | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ActionPlan> | ActionPlan)) => {
  return http.post('*/ai/recommend-action', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetAiActionPlanResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getListAiPredictionsMockHandler = (overrideResponse?: AiPrediction[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<AiPrediction[]> | AiPrediction[])) => {
  return http.get('*/ai/predictions', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getListAiPredictionsResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}
export const getAiMock = () => [
  getAnalyzeDisasterImageMockHandler(),
  getGetAiActionPlanMockHandler(),
  getListAiPredictionsMockHandler()
]
