/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Api
 * Smart Disaster Response and Resource Allocation Platform API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import axios from 'axios'
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  ActionPlan,
  ActionPlanRequest,
  AiPrediction,
  ImageAnalysisRequest,
  ImageAnalysisResult
} from '../../../api-zod/src/generated'

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;



/**
 * @summary Analyze disaster image with AI
 */
export const analyzeDisasterImage = (
    imageAnalysisRequest: ImageAnalysisRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ImageAnalysisResult>> => {
    
    return axios.post(
      `/ai/analyze-image`,
      imageAnalysisRequest,options
    );
  }



export const getAnalyzeDisasterImageMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof analyzeDisasterImage>>, TError,{data: ImageAnalysisRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof analyzeDisasterImage>>, TError,{data: ImageAnalysisRequest}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof analyzeDisasterImage>>, {data: ImageAnalysisRequest}> = (props) => {
          const {data} = props ?? {};

          return  analyzeDisasterImage(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AnalyzeDisasterImageMutationResult = NonNullable<Awaited<ReturnType<typeof analyzeDisasterImage>>>
    export type AnalyzeDisasterImageMutationBody = ImageAnalysisRequest
    export type AnalyzeDisasterImageMutationError = AxiosError<unknown>

    /**
 * @summary Analyze disaster image with AI
 */
export const useAnalyzeDisasterImage = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof analyzeDisasterImage>>, TError,{data: ImageAnalysisRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof analyzeDisasterImage>>,
        TError,
        {data: ImageAnalysisRequest},
        TContext
      > => {

      const mutationOptions = getAnalyzeDisasterImageMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary AI-generated action plan for an incident
 */
export const getAiActionPlan = (
    actionPlanRequest: ActionPlanRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ActionPlan>> => {
    
    return axios.post(
      `/ai/recommend-action`,
      actionPlanRequest,options
    );
  }



export const getGetAiActionPlanMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getAiActionPlan>>, TError,{data: ActionPlanRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof getAiActionPlan>>, TError,{data: ActionPlanRequest}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getAiActionPlan>>, {data: ActionPlanRequest}> = (props) => {
          const {data} = props ?? {};

          return  getAiActionPlan(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type GetAiActionPlanMutationResult = NonNullable<Awaited<ReturnType<typeof getAiActionPlan>>>
    export type GetAiActionPlanMutationBody = ActionPlanRequest
    export type GetAiActionPlanMutationError = AxiosError<unknown>

    /**
 * @summary AI-generated action plan for an incident
 */
export const useGetAiActionPlan = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getAiActionPlan>>, TError,{data: ActionPlanRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof getAiActionPlan>>,
        TError,
        {data: ActionPlanRequest},
        TContext
      > => {

      const mutationOptions = getGetAiActionPlanMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary List recent AI predictions
 */
export const listAiPredictions = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AiPrediction[]>> => {
    
    return axios.get(
      `/ai/predictions`,options
    );
  }


export const getListAiPredictionsQueryKey = () => {
    return [`/ai/predictions`] as const;
    }

    
export const getListAiPredictionsQueryOptions = <TData = Awaited<ReturnType<typeof listAiPredictions>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAiPredictions>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAiPredictionsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAiPredictions>>> = ({ signal }) => listAiPredictions({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAiPredictions>>, TError, TData> & { queryKey: QueryKey }
}

export type ListAiPredictionsQueryResult = NonNullable<Awaited<ReturnType<typeof listAiPredictions>>>
export type ListAiPredictionsQueryError = AxiosError<unknown>

/**
 * @summary List recent AI predictions
 */
export const useListAiPredictions = <TData = Awaited<ReturnType<typeof listAiPredictions>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAiPredictions>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getListAiPredictionsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



