/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Api
 * Smart Disaster Response and Resource Allocation Platform API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import axios from 'axios'
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  RescueRoute,
  RoutePlanRequest,
  RoutePlanResult
} from '../../../api-zod/src/generated'

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;



/**
 * @summary Dijkstra shortest rescue route from team to incident
 */
export const planRescueRoute = (
    routePlanRequest: RoutePlanRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RoutePlanResult>> => {
    
    return axios.post(
      `/routes/plan`,
      routePlanRequest,options
    );
  }



export const getPlanRescueRouteMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof planRescueRoute>>, TError,{data: RoutePlanRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof planRescueRoute>>, TError,{data: RoutePlanRequest}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof planRescueRoute>>, {data: RoutePlanRequest}> = (props) => {
          const {data} = props ?? {};

          return  planRescueRoute(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PlanRescueRouteMutationResult = NonNullable<Awaited<ReturnType<typeof planRescueRoute>>>
    export type PlanRescueRouteMutationBody = RoutePlanRequest
    export type PlanRescueRouteMutationError = AxiosError<unknown>

    /**
 * @summary Dijkstra shortest rescue route from team to incident
 */
export const usePlanRescueRoute = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof planRescueRoute>>, TError,{data: RoutePlanRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof planRescueRoute>>,
        TError,
        {data: RoutePlanRequest},
        TContext
      > => {

      const mutationOptions = getPlanRescueRouteMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary List all saved rescue routes
 */
export const listRoutes = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RescueRoute[]>> => {
    
    return axios.get(
      `/routes`,options
    );
  }


export const getListRoutesQueryKey = () => {
    return [`/routes`] as const;
    }

    
export const getListRoutesQueryOptions = <TData = Awaited<ReturnType<typeof listRoutes>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRoutes>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListRoutesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listRoutes>>> = ({ signal }) => listRoutes({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listRoutes>>, TError, TData> & { queryKey: QueryKey }
}

export type ListRoutesQueryResult = NonNullable<Awaited<ReturnType<typeof listRoutes>>>
export type ListRoutesQueryError = AxiosError<unknown>

/**
 * @summary List all saved rescue routes
 */
export const useListRoutes = <TData = Awaited<ReturnType<typeof listRoutes>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRoutes>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getListRoutesQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



