/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Api
 * Smart Disaster Response and Resource Allocation Platform API
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker'
import {
  HttpResponse,
  delay,
  http
} from 'msw'
import type {
  RescueRoute,
  RoutePlanResult
} from '../../../api-zod/src/generated'

export const getPlanRescueRouteResponseMock = (overrideResponse: Partial< RoutePlanResult > = {}): RoutePlanResult => ({estimatedMinutes: faker.number.int({min: undefined, max: undefined}), routeId: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}),null]), undefined]), safetyScore: faker.number.int({min: undefined, max: undefined}), totalDistanceKm: faker.number.int({min: undefined, max: undefined}), waypoints: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({label: faker.word.sample(), latitude: faker.number.int({min: undefined, max: undefined}), longitude: faker.number.int({min: undefined, max: undefined}), order: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined])})), ...overrideResponse})

export const getListRoutesResponseMock = (): RescueRoute[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({createdAt: faker.word.sample(), estimatedMinutes: faker.number.int({min: undefined, max: undefined}), id: faker.number.int({min: undefined, max: undefined}), incidentId: faker.number.int({min: undefined, max: undefined}), safetyScore: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), status: faker.helpers.arrayElement(['planned','active','completed'] as const), teamId: faker.number.int({min: undefined, max: undefined}), totalDistanceKm: faker.number.int({min: undefined, max: undefined})})))


export const getPlanRescueRouteMockHandler = (overrideResponse?: RoutePlanResult | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<RoutePlanResult> | RoutePlanResult)) => {
  return http.post('*/routes/plan', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getPlanRescueRouteResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getListRoutesMockHandler = (overrideResponse?: RescueRoute[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<RescueRoute[]> | RescueRoute[])) => {
  return http.get('*/routes', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getListRoutesResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}
export const getRoutesMock = () => [
  getPlanRescueRouteMockHandler(),
  getListRoutesMockHandler()
]
