/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Api
 * Smart Disaster Response and Resource Allocation Platform API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import axios from 'axios'
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  AllocationRequest,
  AllocationResult,
  Resource,
  ResourceInput,
  ResourceUpdate,
  ResourceUtilization
} from '../../../api-zod/src/generated'

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;



/**
 * @summary List all resources
 */
export const listResources = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Resource[]>> => {
    
    return axios.get(
      `/resources`,options
    );
  }


export const getListResourcesQueryKey = () => {
    return [`/resources`] as const;
    }

    
export const getListResourcesQueryOptions = <TData = Awaited<ReturnType<typeof listResources>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listResources>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListResourcesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listResources>>> = ({ signal }) => listResources({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listResources>>, TError, TData> & { queryKey: QueryKey }
}

export type ListResourcesQueryResult = NonNullable<Awaited<ReturnType<typeof listResources>>>
export type ListResourcesQueryError = AxiosError<unknown>

/**
 * @summary List all resources
 */
export const useListResources = <TData = Awaited<ReturnType<typeof listResources>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listResources>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getListResourcesQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Add resource
 */
export const createResource = (
    resourceInput: ResourceInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Resource>> => {
    
    return axios.post(
      `/resources`,
      resourceInput,options
    );
  }



export const getCreateResourceMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createResource>>, TError,{data: ResourceInput}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createResource>>, TError,{data: ResourceInput}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createResource>>, {data: ResourceInput}> = (props) => {
          const {data} = props ?? {};

          return  createResource(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateResourceMutationResult = NonNullable<Awaited<ReturnType<typeof createResource>>>
    export type CreateResourceMutationBody = ResourceInput
    export type CreateResourceMutationError = AxiosError<unknown>

    /**
 * @summary Add resource
 */
export const useCreateResource = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createResource>>, TError,{data: ResourceInput}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof createResource>>,
        TError,
        {data: ResourceInput},
        TContext
      > => {

      const mutationOptions = getCreateResourceMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Update resource
 */
export const updateResource = (
    id: number,
    resourceUpdate: ResourceUpdate, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Resource>> => {
    
    return axios.patch(
      `/resources/${id}`,
      resourceUpdate,options
    );
  }



export const getUpdateResourceMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateResource>>, TError,{id: number;data: ResourceUpdate}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateResource>>, TError,{id: number;data: ResourceUpdate}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateResource>>, {id: number;data: ResourceUpdate}> = (props) => {
          const {id,data} = props ?? {};

          return  updateResource(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateResourceMutationResult = NonNullable<Awaited<ReturnType<typeof updateResource>>>
    export type UpdateResourceMutationBody = ResourceUpdate
    export type UpdateResourceMutationError = AxiosError<unknown>

    /**
 * @summary Update resource
 */
export const useUpdateResource = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateResource>>, TError,{id: number;data: ResourceUpdate}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof updateResource>>,
        TError,
        {id: number;data: ResourceUpdate},
        TContext
      > => {

      const mutationOptions = getUpdateResourceMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Run greedy resource allocation for an incident
 */
export const allocateResources = (
    allocationRequest: AllocationRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AllocationResult>> => {
    
    return axios.post(
      `/resources/allocate`,
      allocationRequest,options
    );
  }



export const getAllocateResourcesMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof allocateResources>>, TError,{data: AllocationRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof allocateResources>>, TError,{data: AllocationRequest}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof allocateResources>>, {data: AllocationRequest}> = (props) => {
          const {data} = props ?? {};

          return  allocateResources(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AllocateResourcesMutationResult = NonNullable<Awaited<ReturnType<typeof allocateResources>>>
    export type AllocateResourcesMutationBody = AllocationRequest
    export type AllocateResourcesMutationError = AxiosError<unknown>

    /**
 * @summary Run greedy resource allocation for an incident
 */
export const useAllocateResources = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof allocateResources>>, TError,{data: AllocationRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof allocateResources>>,
        TError,
        {data: AllocationRequest},
        TContext
      > => {

      const mutationOptions = getAllocateResourcesMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Get resource utilization stats per category
 */
export const getResourceUtilization = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ResourceUtilization[]>> => {
    
    return axios.get(
      `/resources/stats/utilization`,options
    );
  }


export const getGetResourceUtilizationQueryKey = () => {
    return [`/resources/stats/utilization`] as const;
    }

    
export const getGetResourceUtilizationQueryOptions = <TData = Awaited<ReturnType<typeof getResourceUtilization>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getResourceUtilization>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetResourceUtilizationQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getResourceUtilization>>> = ({ signal }) => getResourceUtilization({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getResourceUtilization>>, TError, TData> & { queryKey: QueryKey }
}

export type GetResourceUtilizationQueryResult = NonNullable<Awaited<ReturnType<typeof getResourceUtilization>>>
export type GetResourceUtilizationQueryError = AxiosError<unknown>

/**
 * @summary Get resource utilization stats per category
 */
export const useGetResourceUtilization = <TData = Awaited<ReturnType<typeof getResourceUtilization>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getResourceUtilization>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetResourceUtilizationQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



