/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Api
 * Smart Disaster Response and Resource Allocation Platform API
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker'
import {
  HttpResponse,
  delay,
  http
} from 'msw'
import type {
  AllocationResult,
  Resource,
  ResourceUtilization
} from '../../../api-zod/src/generated'

export const getListResourcesResponseMock = (): Resource[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({availableQuantity: faker.number.int({min: undefined, max: undefined}), category: faker.helpers.arrayElement(['food','water','medical','rescue_team','boat','ambulance'] as const), id: faker.number.int({min: undefined, max: undefined}), latitude: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}),null]), undefined]), location: faker.word.sample(), longitude: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}),null]), undefined]), name: faker.word.sample(), totalQuantity: faker.number.int({min: undefined, max: undefined}), unit: faker.word.sample()})))

export const getCreateResourceResponseMock = (overrideResponse: Partial< Resource > = {}): Resource => ({availableQuantity: faker.number.int({min: undefined, max: undefined}), category: faker.helpers.arrayElement(['food','water','medical','rescue_team','boat','ambulance'] as const), id: faker.number.int({min: undefined, max: undefined}), latitude: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}),null]), undefined]), location: faker.word.sample(), longitude: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}),null]), undefined]), name: faker.word.sample(), totalQuantity: faker.number.int({min: undefined, max: undefined}), unit: faker.word.sample(), ...overrideResponse})

export const getUpdateResourceResponseMock = (overrideResponse: Partial< Resource > = {}): Resource => ({availableQuantity: faker.number.int({min: undefined, max: undefined}), category: faker.helpers.arrayElement(['food','water','medical','rescue_team','boat','ambulance'] as const), id: faker.number.int({min: undefined, max: undefined}), latitude: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}),null]), undefined]), location: faker.word.sample(), longitude: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}),null]), undefined]), name: faker.word.sample(), totalQuantity: faker.number.int({min: undefined, max: undefined}), unit: faker.word.sample(), ...overrideResponse})

export const getAllocateResourcesResponseMock = (overrideResponse: Partial< AllocationResult > = {}): AllocationResult => ({allocations: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({allocated: faker.number.int({min: undefined, max: undefined}), category: faker.word.sample(), resourceId: faker.number.int({min: undefined, max: undefined}), resourceName: faker.word.sample(), unit: faker.word.sample()})), efficiencyScore: faker.number.int({min: undefined, max: undefined}), incidentId: faker.number.int({min: undefined, max: undefined}), shortages: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), ...overrideResponse})

export const getGetResourceUtilizationResponseMock = (): ResourceUtilization[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({available: faker.number.int({min: undefined, max: undefined}), category: faker.word.sample(), total: faker.number.int({min: undefined, max: undefined}), used: faker.number.int({min: undefined, max: undefined}), utilizationPct: faker.number.int({min: undefined, max: undefined})})))


export const getListResourcesMockHandler = (overrideResponse?: Resource[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Resource[]> | Resource[])) => {
  return http.get('*/resources', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getListResourcesResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getCreateResourceMockHandler = (overrideResponse?: Resource | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Resource> | Resource)) => {
  return http.post('*/resources', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getCreateResourceResponseMock()),
      {
        status: 201,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getUpdateResourceMockHandler = (overrideResponse?: Resource | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<Resource> | Resource)) => {
  return http.patch('*/resources/:id', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getUpdateResourceResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getAllocateResourcesMockHandler = (overrideResponse?: AllocationResult | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<AllocationResult> | AllocationResult)) => {
  return http.post('*/resources/allocate', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getAllocateResourcesResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetResourceUtilizationMockHandler = (overrideResponse?: ResourceUtilization[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ResourceUtilization[]> | ResourceUtilization[])) => {
  return http.get('*/resources/stats/utilization', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetResourceUtilizationResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}
export const getResourcesMock = () => [
  getListResourcesMockHandler(),
  getCreateResourceMockHandler(),
  getUpdateResourceMockHandler(),
  getAllocateResourcesMockHandler(),
  getGetResourceUtilizationMockHandler()
]
