/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Api
 * Smart Disaster Response and Resource Allocation Platform API
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker'
import {
  HttpResponse,
  delay,
  http
} from 'msw'
import type {
  CategoryCount,
  Incident,
  IncidentSummary,
  TrendPoint
} from '../../../api-zod/src/generated'

export const getListIncidentsResponseMock = (): Incident[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({affectedPopulation: faker.number.int({min: undefined, max: undefined}), category: faker.helpers.arrayElement(['flood','earthquake','cyclone','fire','landslide'] as const), createdAt: faker.word.sample(), description: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined]), id: faker.number.int({min: undefined, max: undefined}), imageUrl: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined]), latitude: faker.number.int({min: undefined, max: undefined}), longitude: faker.number.int({min: undefined, max: undefined}), region: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined]), severity: faker.number.int({min: 1, max: 10}), status: faker.helpers.arrayElement(['active','resolved','monitoring','critical'] as const), title: faker.word.sample(), updatedAt: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined])})))

export const getCreateIncidentResponseMock = (overrideResponse: Partial< Incident > = {}): Incident => ({affectedPopulation: faker.number.int({min: undefined, max: undefined}), category: faker.helpers.arrayElement(['flood','earthquake','cyclone','fire','landslide'] as const), createdAt: faker.word.sample(), description: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined]), id: faker.number.int({min: undefined, max: undefined}), imageUrl: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined]), latitude: faker.number.int({min: undefined, max: undefined}), longitude: faker.number.int({min: undefined, max: undefined}), region: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined]), severity: faker.number.int({min: 1, max: 10}), status: faker.helpers.arrayElement(['active','resolved','monitoring','critical'] as const), title: faker.word.sample(), updatedAt: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined]), ...overrideResponse})

export const getGetIncidentResponseMock = (overrideResponse: Partial< Incident > = {}): Incident => ({affectedPopulation: faker.number.int({min: undefined, max: undefined}), category: faker.helpers.arrayElement(['flood','earthquake','cyclone','fire','landslide'] as const), createdAt: faker.word.sample(), description: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined]), id: faker.number.int({min: undefined, max: undefined}), imageUrl: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined]), latitude: faker.number.int({min: undefined, max: undefined}), longitude: faker.number.int({min: undefined, max: undefined}), region: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined]), severity: faker.number.int({min: 1, max: 10}), status: faker.helpers.arrayElement(['active','resolved','monitoring','critical'] as const), title: faker.word.sample(), updatedAt: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined]), ...overrideResponse})

export const getUpdateIncidentResponseMock = (overrideResponse: Partial< Incident > = {}): Incident => ({affectedPopulation: faker.number.int({min: undefined, max: undefined}), category: faker.helpers.arrayElement(['flood','earthquake','cyclone','fire','landslide'] as const), createdAt: faker.word.sample(), description: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined]), id: faker.number.int({min: undefined, max: undefined}), imageUrl: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined]), latitude: faker.number.int({min: undefined, max: undefined}), longitude: faker.number.int({min: undefined, max: undefined}), region: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined]), severity: faker.number.int({min: 1, max: 10}), status: faker.helpers.arrayElement(['active','resolved','monitoring','critical'] as const), title: faker.word.sample(), updatedAt: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined]), ...overrideResponse})

export const getGetIncidentSummaryResponseMock = (overrideResponse: Partial< IncidentSummary > = {}): IncidentSummary => ({activeRescueOps: faker.number.int({min: undefined, max: undefined}), criticalIncidents: faker.number.int({min: undefined, max: undefined}), populationAffected: faker.number.int({min: undefined, max: undefined}), resourceUtilizationPct: faker.number.int({min: undefined, max: undefined}), shelterOccupancy: faker.number.int({min: undefined, max: undefined}), totalIncidents: faker.number.int({min: undefined, max: undefined}), ...overrideResponse})

export const getGetIncidentTrendsResponseMock = (): TrendPoint[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({count: faker.number.int({min: undefined, max: undefined}), date: faker.word.sample(), severity: faker.number.int({min: undefined, max: undefined})})))

export const getGetIncidentsByCategoryResponseMock = (): CategoryCount[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({category: faker.word.sample(), count: faker.number.int({min: undefined, max: undefined}), populationAffected: faker.number.int({min: undefined, max: undefined})})))


export const getListIncidentsMockHandler = (overrideResponse?: Incident[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Incident[]> | Incident[])) => {
  return http.get('*/incidents', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getListIncidentsResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getCreateIncidentMockHandler = (overrideResponse?: Incident | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Incident> | Incident)) => {
  return http.post('*/incidents', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getCreateIncidentResponseMock()),
      {
        status: 201,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetIncidentMockHandler = (overrideResponse?: Incident | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Incident> | Incident)) => {
  return http.get('*/incidents/:id', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetIncidentResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getUpdateIncidentMockHandler = (overrideResponse?: Incident | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<Incident> | Incident)) => {
  return http.patch('*/incidents/:id', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getUpdateIncidentResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getDeleteIncidentMockHandler = () => {
  return http.delete('*/incidents/:id', async () => {await delay(1000);
    return new HttpResponse(null,
      {
        status: 204,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetIncidentSummaryMockHandler = (overrideResponse?: IncidentSummary | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<IncidentSummary> | IncidentSummary)) => {
  return http.get('*/incidents/stats/summary', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetIncidentSummaryResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetIncidentTrendsMockHandler = (overrideResponse?: TrendPoint[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<TrendPoint[]> | TrendPoint[])) => {
  return http.get('*/incidents/stats/trends', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetIncidentTrendsResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetIncidentsByCategoryMockHandler = (overrideResponse?: CategoryCount[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<CategoryCount[]> | CategoryCount[])) => {
  return http.get('*/incidents/stats/by-category', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetIncidentsByCategoryResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}
export const getIncidentsMock = () => [
  getListIncidentsMockHandler(),
  getCreateIncidentMockHandler(),
  getGetIncidentMockHandler(),
  getUpdateIncidentMockHandler(),
  getDeleteIncidentMockHandler(),
  getGetIncidentSummaryMockHandler(),
  getGetIncidentTrendsMockHandler(),
  getGetIncidentsByCategoryMockHandler()
]
