/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Api
 * Smart Disaster Response and Resource Allocation Platform API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import axios from 'axios'
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  CategoryCount,
  Incident,
  IncidentInput,
  IncidentSummary,
  IncidentUpdate,
  ListIncidentsParams,
  TrendPoint
} from '../../../api-zod/src/generated'

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;



/**
 * @summary List all incidents
 */
export const listIncidents = (
    params?: ListIncidentsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Incident[]>> => {
    
    return axios.get(
      `/incidents`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getListIncidentsQueryKey = (params?: ListIncidentsParams,) => {
    return [`/incidents`, ...(params ? [params]: [])] as const;
    }

    
export const getListIncidentsQueryOptions = <TData = Awaited<ReturnType<typeof listIncidents>>, TError = AxiosError<unknown>>(params?: ListIncidentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listIncidents>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListIncidentsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listIncidents>>> = ({ signal }) => listIncidents(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listIncidents>>, TError, TData> & { queryKey: QueryKey }
}

export type ListIncidentsQueryResult = NonNullable<Awaited<ReturnType<typeof listIncidents>>>
export type ListIncidentsQueryError = AxiosError<unknown>

/**
 * @summary List all incidents
 */
export const useListIncidents = <TData = Awaited<ReturnType<typeof listIncidents>>, TError = AxiosError<unknown>>(
 params?: ListIncidentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listIncidents>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getListIncidentsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Create a new disaster incident
 */
export const createIncident = (
    incidentInput: IncidentInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Incident>> => {
    
    return axios.post(
      `/incidents`,
      incidentInput,options
    );
  }



export const getCreateIncidentMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createIncident>>, TError,{data: IncidentInput}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createIncident>>, TError,{data: IncidentInput}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createIncident>>, {data: IncidentInput}> = (props) => {
          const {data} = props ?? {};

          return  createIncident(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateIncidentMutationResult = NonNullable<Awaited<ReturnType<typeof createIncident>>>
    export type CreateIncidentMutationBody = IncidentInput
    export type CreateIncidentMutationError = AxiosError<unknown>

    /**
 * @summary Create a new disaster incident
 */
export const useCreateIncident = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createIncident>>, TError,{data: IncidentInput}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof createIncident>>,
        TError,
        {data: IncidentInput},
        TContext
      > => {

      const mutationOptions = getCreateIncidentMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Get incident by ID
 */
export const getIncident = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Incident>> => {
    
    return axios.get(
      `/incidents/${id}`,options
    );
  }


export const getGetIncidentQueryKey = (id: number,) => {
    return [`/incidents/${id}`] as const;
    }

    
export const getGetIncidentQueryOptions = <TData = Awaited<ReturnType<typeof getIncident>>, TError = AxiosError<void>>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIncident>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetIncidentQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getIncident>>> = ({ signal }) => getIncident(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getIncident>>, TError, TData> & { queryKey: QueryKey }
}

export type GetIncidentQueryResult = NonNullable<Awaited<ReturnType<typeof getIncident>>>
export type GetIncidentQueryError = AxiosError<void>

/**
 * @summary Get incident by ID
 */
export const useGetIncident = <TData = Awaited<ReturnType<typeof getIncident>>, TError = AxiosError<void>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIncident>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetIncidentQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Update incident
 */
export const updateIncident = (
    id: number,
    incidentUpdate: IncidentUpdate, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Incident>> => {
    
    return axios.patch(
      `/incidents/${id}`,
      incidentUpdate,options
    );
  }



export const getUpdateIncidentMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateIncident>>, TError,{id: number;data: IncidentUpdate}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateIncident>>, TError,{id: number;data: IncidentUpdate}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateIncident>>, {id: number;data: IncidentUpdate}> = (props) => {
          const {id,data} = props ?? {};

          return  updateIncident(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateIncidentMutationResult = NonNullable<Awaited<ReturnType<typeof updateIncident>>>
    export type UpdateIncidentMutationBody = IncidentUpdate
    export type UpdateIncidentMutationError = AxiosError<unknown>

    /**
 * @summary Update incident
 */
export const useUpdateIncident = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateIncident>>, TError,{id: number;data: IncidentUpdate}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof updateIncident>>,
        TError,
        {id: number;data: IncidentUpdate},
        TContext
      > => {

      const mutationOptions = getUpdateIncidentMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Delete incident
 */
export const deleteIncident = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    return axios.delete(
      `/incidents/${id}`,options
    );
  }



export const getDeleteIncidentMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteIncident>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteIncident>>, TError,{id: number}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteIncident>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteIncident(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteIncidentMutationResult = NonNullable<Awaited<ReturnType<typeof deleteIncident>>>
    
    export type DeleteIncidentMutationError = AxiosError<unknown>

    /**
 * @summary Delete incident
 */
export const useDeleteIncident = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteIncident>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof deleteIncident>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteIncidentMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Get dashboard summary stats
 */
export const getIncidentSummary = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<IncidentSummary>> => {
    
    return axios.get(
      `/incidents/stats/summary`,options
    );
  }


export const getGetIncidentSummaryQueryKey = () => {
    return [`/incidents/stats/summary`] as const;
    }

    
export const getGetIncidentSummaryQueryOptions = <TData = Awaited<ReturnType<typeof getIncidentSummary>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIncidentSummary>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetIncidentSummaryQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getIncidentSummary>>> = ({ signal }) => getIncidentSummary({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getIncidentSummary>>, TError, TData> & { queryKey: QueryKey }
}

export type GetIncidentSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getIncidentSummary>>>
export type GetIncidentSummaryQueryError = AxiosError<unknown>

/**
 * @summary Get dashboard summary stats
 */
export const useGetIncidentSummary = <TData = Awaited<ReturnType<typeof getIncidentSummary>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIncidentSummary>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetIncidentSummaryQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get incident trends by day
 */
export const getIncidentTrends = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TrendPoint[]>> => {
    
    return axios.get(
      `/incidents/stats/trends`,options
    );
  }


export const getGetIncidentTrendsQueryKey = () => {
    return [`/incidents/stats/trends`] as const;
    }

    
export const getGetIncidentTrendsQueryOptions = <TData = Awaited<ReturnType<typeof getIncidentTrends>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIncidentTrends>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetIncidentTrendsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getIncidentTrends>>> = ({ signal }) => getIncidentTrends({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getIncidentTrends>>, TError, TData> & { queryKey: QueryKey }
}

export type GetIncidentTrendsQueryResult = NonNullable<Awaited<ReturnType<typeof getIncidentTrends>>>
export type GetIncidentTrendsQueryError = AxiosError<unknown>

/**
 * @summary Get incident trends by day
 */
export const useGetIncidentTrends = <TData = Awaited<ReturnType<typeof getIncidentTrends>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIncidentTrends>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetIncidentTrendsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Count incidents grouped by category
 */
export const getIncidentsByCategory = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CategoryCount[]>> => {
    
    return axios.get(
      `/incidents/stats/by-category`,options
    );
  }


export const getGetIncidentsByCategoryQueryKey = () => {
    return [`/incidents/stats/by-category`] as const;
    }

    
export const getGetIncidentsByCategoryQueryOptions = <TData = Awaited<ReturnType<typeof getIncidentsByCategory>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIncidentsByCategory>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetIncidentsByCategoryQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getIncidentsByCategory>>> = ({ signal }) => getIncidentsByCategory({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getIncidentsByCategory>>, TError, TData> & { queryKey: QueryKey }
}

export type GetIncidentsByCategoryQueryResult = NonNullable<Awaited<ReturnType<typeof getIncidentsByCategory>>>
export type GetIncidentsByCategoryQueryError = AxiosError<unknown>

/**
 * @summary Count incidents grouped by category
 */
export const useGetIncidentsByCategory = <TData = Awaited<ReturnType<typeof getIncidentsByCategory>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIncidentsByCategory>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetIncidentsByCategoryQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



