/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Api
 * Smart Disaster Response and Resource Allocation Platform API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  ActionPlanRequest,
  AllocationRequest,
  ImageAnalysisRequest,
  IncidentInput,
  IncidentUpdate,
  ListIncidentsParams,
  RescueTeamInput,
  RescueTeamUpdate,
  ResourceInput,
  ResourceUpdate,
  RoutePlanRequest,
  ShelterInput,
  ShelterRecommendRequest,
  ShelterUpdate
} from '../../api-zod/src/generated'
import {
  faker
} from '@faker-js/faker'
import {
  HttpResponse,
  delay,
  http
} from 'msw'
import type {
  ActionPlan,
  AiPrediction,
  AllocationResult,
  CategoryCount,
  HealthStatus,
  ImageAnalysisResult,
  Incident,
  IncidentSummary,
  RegionImpact,
  RescueEfficiency,
  RescueRoute,
  RescueTeam,
  Resource,
  ResourceUtilization,
  RoutePlanResult,
  Shelter,
  ShelterRecommendation,
  TickerEvent,
  TrendPoint
} from '../../api-zod/src/generated'
import { customInstance } from '../../api-spec/mutator';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


/**
 * @summary Health check
 */
export const healthCheck = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<HealthStatus>(
      {url: `/healthz`, method: 'GET', signal
    },
      options);
    }
  

export const getHealthCheckQueryKey = () => {
    return [`/healthz`] as const;
    }

    
export const getHealthCheckQueryOptions = <TData = Awaited<ReturnType<typeof healthCheck>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({ signal }) => healthCheck(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthCheckQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheck>>>
export type HealthCheckQueryError = unknown

/**
 * @summary Health check
 */
export const useHealthCheck = <TData = Awaited<ReturnType<typeof healthCheck>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getHealthCheckQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary List all incidents
 */
export const listIncidents = (
    params?: ListIncidentsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Incident[]>(
      {url: `/incidents`, method: 'GET',
        params, signal
    },
      options);
    }
  

export const getListIncidentsQueryKey = (params?: ListIncidentsParams,) => {
    return [`/incidents`, ...(params ? [params]: [])] as const;
    }

    
export const getListIncidentsQueryOptions = <TData = Awaited<ReturnType<typeof listIncidents>>, TError = unknown>(params?: ListIncidentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listIncidents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListIncidentsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listIncidents>>> = ({ signal }) => listIncidents(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listIncidents>>, TError, TData> & { queryKey: QueryKey }
}

export type ListIncidentsQueryResult = NonNullable<Awaited<ReturnType<typeof listIncidents>>>
export type ListIncidentsQueryError = unknown

/**
 * @summary List all incidents
 */
export const useListIncidents = <TData = Awaited<ReturnType<typeof listIncidents>>, TError = unknown>(
 params?: ListIncidentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listIncidents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getListIncidentsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create a new disaster incident
 */
export const createIncident = (
    incidentInput: IncidentInput,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<Incident>(
      {url: `/incidents`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: incidentInput
    },
      options);
    }
  


export const getCreateIncidentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createIncident>>, TError,{data: IncidentInput}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createIncident>>, TError,{data: IncidentInput}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createIncident>>, {data: IncidentInput}> = (props) => {
          const {data} = props ?? {};

          return  createIncident(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateIncidentMutationResult = NonNullable<Awaited<ReturnType<typeof createIncident>>>
    export type CreateIncidentMutationBody = IncidentInput
    export type CreateIncidentMutationError = unknown

    /**
 * @summary Create a new disaster incident
 */
export const useCreateIncident = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createIncident>>, TError,{data: IncidentInput}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof createIncident>>,
        TError,
        {data: IncidentInput},
        TContext
      > => {

      const mutationOptions = getCreateIncidentMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Get incident by ID
 */
export const getIncident = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Incident>(
      {url: `/incidents/${id}`, method: 'GET', signal
    },
      options);
    }
  

export const getGetIncidentQueryKey = (id: number,) => {
    return [`/incidents/${id}`] as const;
    }

    
export const getGetIncidentQueryOptions = <TData = Awaited<ReturnType<typeof getIncident>>, TError = void>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIncident>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetIncidentQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getIncident>>> = ({ signal }) => getIncident(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getIncident>>, TError, TData> & { queryKey: QueryKey }
}

export type GetIncidentQueryResult = NonNullable<Awaited<ReturnType<typeof getIncident>>>
export type GetIncidentQueryError = void

/**
 * @summary Get incident by ID
 */
export const useGetIncident = <TData = Awaited<ReturnType<typeof getIncident>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIncident>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetIncidentQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update incident
 */
export const updateIncident = (
    id: number,
    incidentUpdate: IncidentUpdate,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<Incident>(
      {url: `/incidents/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: incidentUpdate
    },
      options);
    }
  


export const getUpdateIncidentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateIncident>>, TError,{id: number;data: IncidentUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateIncident>>, TError,{id: number;data: IncidentUpdate}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateIncident>>, {id: number;data: IncidentUpdate}> = (props) => {
          const {id,data} = props ?? {};

          return  updateIncident(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateIncidentMutationResult = NonNullable<Awaited<ReturnType<typeof updateIncident>>>
    export type UpdateIncidentMutationBody = IncidentUpdate
    export type UpdateIncidentMutationError = unknown

    /**
 * @summary Update incident
 */
export const useUpdateIncident = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateIncident>>, TError,{id: number;data: IncidentUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof updateIncident>>,
        TError,
        {id: number;data: IncidentUpdate},
        TContext
      > => {

      const mutationOptions = getUpdateIncidentMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Delete incident
 */
export const deleteIncident = (
    id: number,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/incidents/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteIncidentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteIncident>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteIncident>>, TError,{id: number}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteIncident>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteIncident(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteIncidentMutationResult = NonNullable<Awaited<ReturnType<typeof deleteIncident>>>
    
    export type DeleteIncidentMutationError = unknown

    /**
 * @summary Delete incident
 */
export const useDeleteIncident = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteIncident>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof deleteIncident>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteIncidentMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Get dashboard summary stats
 */
export const getIncidentSummary = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<IncidentSummary>(
      {url: `/incidents/stats/summary`, method: 'GET', signal
    },
      options);
    }
  

export const getGetIncidentSummaryQueryKey = () => {
    return [`/incidents/stats/summary`] as const;
    }

    
export const getGetIncidentSummaryQueryOptions = <TData = Awaited<ReturnType<typeof getIncidentSummary>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIncidentSummary>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetIncidentSummaryQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getIncidentSummary>>> = ({ signal }) => getIncidentSummary(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getIncidentSummary>>, TError, TData> & { queryKey: QueryKey }
}

export type GetIncidentSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getIncidentSummary>>>
export type GetIncidentSummaryQueryError = unknown

/**
 * @summary Get dashboard summary stats
 */
export const useGetIncidentSummary = <TData = Awaited<ReturnType<typeof getIncidentSummary>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIncidentSummary>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetIncidentSummaryQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get incident trends by day
 */
export const getIncidentTrends = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<TrendPoint[]>(
      {url: `/incidents/stats/trends`, method: 'GET', signal
    },
      options);
    }
  

export const getGetIncidentTrendsQueryKey = () => {
    return [`/incidents/stats/trends`] as const;
    }

    
export const getGetIncidentTrendsQueryOptions = <TData = Awaited<ReturnType<typeof getIncidentTrends>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIncidentTrends>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetIncidentTrendsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getIncidentTrends>>> = ({ signal }) => getIncidentTrends(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getIncidentTrends>>, TError, TData> & { queryKey: QueryKey }
}

export type GetIncidentTrendsQueryResult = NonNullable<Awaited<ReturnType<typeof getIncidentTrends>>>
export type GetIncidentTrendsQueryError = unknown

/**
 * @summary Get incident trends by day
 */
export const useGetIncidentTrends = <TData = Awaited<ReturnType<typeof getIncidentTrends>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIncidentTrends>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetIncidentTrendsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Count incidents grouped by category
 */
export const getIncidentsByCategory = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<CategoryCount[]>(
      {url: `/incidents/stats/by-category`, method: 'GET', signal
    },
      options);
    }
  

export const getGetIncidentsByCategoryQueryKey = () => {
    return [`/incidents/stats/by-category`] as const;
    }

    
export const getGetIncidentsByCategoryQueryOptions = <TData = Awaited<ReturnType<typeof getIncidentsByCategory>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIncidentsByCategory>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetIncidentsByCategoryQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getIncidentsByCategory>>> = ({ signal }) => getIncidentsByCategory(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getIncidentsByCategory>>, TError, TData> & { queryKey: QueryKey }
}

export type GetIncidentsByCategoryQueryResult = NonNullable<Awaited<ReturnType<typeof getIncidentsByCategory>>>
export type GetIncidentsByCategoryQueryError = unknown

/**
 * @summary Count incidents grouped by category
 */
export const useGetIncidentsByCategory = <TData = Awaited<ReturnType<typeof getIncidentsByCategory>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIncidentsByCategory>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetIncidentsByCategoryQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary List all resources
 */
export const listResources = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Resource[]>(
      {url: `/resources`, method: 'GET', signal
    },
      options);
    }
  

export const getListResourcesQueryKey = () => {
    return [`/resources`] as const;
    }

    
export const getListResourcesQueryOptions = <TData = Awaited<ReturnType<typeof listResources>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listResources>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListResourcesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listResources>>> = ({ signal }) => listResources(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listResources>>, TError, TData> & { queryKey: QueryKey }
}

export type ListResourcesQueryResult = NonNullable<Awaited<ReturnType<typeof listResources>>>
export type ListResourcesQueryError = unknown

/**
 * @summary List all resources
 */
export const useListResources = <TData = Awaited<ReturnType<typeof listResources>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listResources>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getListResourcesQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Add resource
 */
export const createResource = (
    resourceInput: ResourceInput,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<Resource>(
      {url: `/resources`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: resourceInput
    },
      options);
    }
  


export const getCreateResourceMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createResource>>, TError,{data: ResourceInput}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createResource>>, TError,{data: ResourceInput}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createResource>>, {data: ResourceInput}> = (props) => {
          const {data} = props ?? {};

          return  createResource(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateResourceMutationResult = NonNullable<Awaited<ReturnType<typeof createResource>>>
    export type CreateResourceMutationBody = ResourceInput
    export type CreateResourceMutationError = unknown

    /**
 * @summary Add resource
 */
export const useCreateResource = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createResource>>, TError,{data: ResourceInput}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof createResource>>,
        TError,
        {data: ResourceInput},
        TContext
      > => {

      const mutationOptions = getCreateResourceMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Update resource
 */
export const updateResource = (
    id: number,
    resourceUpdate: ResourceUpdate,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<Resource>(
      {url: `/resources/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: resourceUpdate
    },
      options);
    }
  


export const getUpdateResourceMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateResource>>, TError,{id: number;data: ResourceUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateResource>>, TError,{id: number;data: ResourceUpdate}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateResource>>, {id: number;data: ResourceUpdate}> = (props) => {
          const {id,data} = props ?? {};

          return  updateResource(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateResourceMutationResult = NonNullable<Awaited<ReturnType<typeof updateResource>>>
    export type UpdateResourceMutationBody = ResourceUpdate
    export type UpdateResourceMutationError = unknown

    /**
 * @summary Update resource
 */
export const useUpdateResource = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateResource>>, TError,{id: number;data: ResourceUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof updateResource>>,
        TError,
        {id: number;data: ResourceUpdate},
        TContext
      > => {

      const mutationOptions = getUpdateResourceMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Run greedy resource allocation for an incident
 */
export const allocateResources = (
    allocationRequest: AllocationRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<AllocationResult>(
      {url: `/resources/allocate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: allocationRequest
    },
      options);
    }
  


export const getAllocateResourcesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof allocateResources>>, TError,{data: AllocationRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof allocateResources>>, TError,{data: AllocationRequest}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof allocateResources>>, {data: AllocationRequest}> = (props) => {
          const {data} = props ?? {};

          return  allocateResources(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AllocateResourcesMutationResult = NonNullable<Awaited<ReturnType<typeof allocateResources>>>
    export type AllocateResourcesMutationBody = AllocationRequest
    export type AllocateResourcesMutationError = unknown

    /**
 * @summary Run greedy resource allocation for an incident
 */
export const useAllocateResources = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof allocateResources>>, TError,{data: AllocationRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof allocateResources>>,
        TError,
        {data: AllocationRequest},
        TContext
      > => {

      const mutationOptions = getAllocateResourcesMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Get resource utilization stats per category
 */
export const getResourceUtilization = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ResourceUtilization[]>(
      {url: `/resources/stats/utilization`, method: 'GET', signal
    },
      options);
    }
  

export const getGetResourceUtilizationQueryKey = () => {
    return [`/resources/stats/utilization`] as const;
    }

    
export const getGetResourceUtilizationQueryOptions = <TData = Awaited<ReturnType<typeof getResourceUtilization>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getResourceUtilization>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetResourceUtilizationQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getResourceUtilization>>> = ({ signal }) => getResourceUtilization(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getResourceUtilization>>, TError, TData> & { queryKey: QueryKey }
}

export type GetResourceUtilizationQueryResult = NonNullable<Awaited<ReturnType<typeof getResourceUtilization>>>
export type GetResourceUtilizationQueryError = unknown

/**
 * @summary Get resource utilization stats per category
 */
export const useGetResourceUtilization = <TData = Awaited<ReturnType<typeof getResourceUtilization>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getResourceUtilization>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetResourceUtilizationQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary List all shelters
 */
export const listShelters = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Shelter[]>(
      {url: `/shelters`, method: 'GET', signal
    },
      options);
    }
  

export const getListSheltersQueryKey = () => {
    return [`/shelters`] as const;
    }

    
export const getListSheltersQueryOptions = <TData = Awaited<ReturnType<typeof listShelters>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listShelters>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSheltersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listShelters>>> = ({ signal }) => listShelters(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listShelters>>, TError, TData> & { queryKey: QueryKey }
}

export type ListSheltersQueryResult = NonNullable<Awaited<ReturnType<typeof listShelters>>>
export type ListSheltersQueryError = unknown

/**
 * @summary List all shelters
 */
export const useListShelters = <TData = Awaited<ReturnType<typeof listShelters>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listShelters>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getListSheltersQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Add a shelter
 */
export const createShelter = (
    shelterInput: ShelterInput,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<Shelter>(
      {url: `/shelters`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: shelterInput
    },
      options);
    }
  


export const getCreateShelterMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createShelter>>, TError,{data: ShelterInput}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createShelter>>, TError,{data: ShelterInput}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createShelter>>, {data: ShelterInput}> = (props) => {
          const {data} = props ?? {};

          return  createShelter(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateShelterMutationResult = NonNullable<Awaited<ReturnType<typeof createShelter>>>
    export type CreateShelterMutationBody = ShelterInput
    export type CreateShelterMutationError = unknown

    /**
 * @summary Add a shelter
 */
export const useCreateShelter = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createShelter>>, TError,{data: ShelterInput}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof createShelter>>,
        TError,
        {data: ShelterInput},
        TContext
      > => {

      const mutationOptions = getCreateShelterMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Update shelter
 */
export const updateShelter = (
    id: number,
    shelterUpdate: ShelterUpdate,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<Shelter>(
      {url: `/shelters/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: shelterUpdate
    },
      options);
    }
  


export const getUpdateShelterMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateShelter>>, TError,{id: number;data: ShelterUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateShelter>>, TError,{id: number;data: ShelterUpdate}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateShelter>>, {id: number;data: ShelterUpdate}> = (props) => {
          const {id,data} = props ?? {};

          return  updateShelter(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateShelterMutationResult = NonNullable<Awaited<ReturnType<typeof updateShelter>>>
    export type UpdateShelterMutationBody = ShelterUpdate
    export type UpdateShelterMutationError = unknown

    /**
 * @summary Update shelter
 */
export const useUpdateShelter = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateShelter>>, TError,{id: number;data: ShelterUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof updateShelter>>,
        TError,
        {id: number;data: ShelterUpdate},
        TContext
      > => {

      const mutationOptions = getUpdateShelterMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Delete shelter
 */
export const deleteShelter = (
    id: number,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/shelters/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteShelterMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteShelter>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteShelter>>, TError,{id: number}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteShelter>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteShelter(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteShelterMutationResult = NonNullable<Awaited<ReturnType<typeof deleteShelter>>>
    
    export type DeleteShelterMutationError = unknown

    /**
 * @summary Delete shelter
 */
export const useDeleteShelter = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteShelter>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof deleteShelter>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteShelterMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary BFS-based shelter recommendation for incident
 */
export const recommendShelters = (
    shelterRecommendRequest: ShelterRecommendRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<ShelterRecommendation[]>(
      {url: `/shelters/recommend`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: shelterRecommendRequest
    },
      options);
    }
  


export const getRecommendSheltersMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof recommendShelters>>, TError,{data: ShelterRecommendRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof recommendShelters>>, TError,{data: ShelterRecommendRequest}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof recommendShelters>>, {data: ShelterRecommendRequest}> = (props) => {
          const {data} = props ?? {};

          return  recommendShelters(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RecommendSheltersMutationResult = NonNullable<Awaited<ReturnType<typeof recommendShelters>>>
    export type RecommendSheltersMutationBody = ShelterRecommendRequest
    export type RecommendSheltersMutationError = unknown

    /**
 * @summary BFS-based shelter recommendation for incident
 */
export const useRecommendShelters = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof recommendShelters>>, TError,{data: ShelterRecommendRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof recommendShelters>>,
        TError,
        {data: ShelterRecommendRequest},
        TContext
      > => {

      const mutationOptions = getRecommendSheltersMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary List rescue teams
 */
export const listRescueTeams = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RescueTeam[]>(
      {url: `/rescue-teams`, method: 'GET', signal
    },
      options);
    }
  

export const getListRescueTeamsQueryKey = () => {
    return [`/rescue-teams`] as const;
    }

    
export const getListRescueTeamsQueryOptions = <TData = Awaited<ReturnType<typeof listRescueTeams>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRescueTeams>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListRescueTeamsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listRescueTeams>>> = ({ signal }) => listRescueTeams(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listRescueTeams>>, TError, TData> & { queryKey: QueryKey }
}

export type ListRescueTeamsQueryResult = NonNullable<Awaited<ReturnType<typeof listRescueTeams>>>
export type ListRescueTeamsQueryError = unknown

/**
 * @summary List rescue teams
 */
export const useListRescueTeams = <TData = Awaited<ReturnType<typeof listRescueTeams>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRescueTeams>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getListRescueTeamsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Register a rescue team
 */
export const createRescueTeam = (
    rescueTeamInput: RescueTeamInput,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<RescueTeam>(
      {url: `/rescue-teams`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: rescueTeamInput
    },
      options);
    }
  


export const getCreateRescueTeamMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRescueTeam>>, TError,{data: RescueTeamInput}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createRescueTeam>>, TError,{data: RescueTeamInput}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createRescueTeam>>, {data: RescueTeamInput}> = (props) => {
          const {data} = props ?? {};

          return  createRescueTeam(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateRescueTeamMutationResult = NonNullable<Awaited<ReturnType<typeof createRescueTeam>>>
    export type CreateRescueTeamMutationBody = RescueTeamInput
    export type CreateRescueTeamMutationError = unknown

    /**
 * @summary Register a rescue team
 */
export const useCreateRescueTeam = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRescueTeam>>, TError,{data: RescueTeamInput}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof createRescueTeam>>,
        TError,
        {data: RescueTeamInput},
        TContext
      > => {

      const mutationOptions = getCreateRescueTeamMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Update rescue team
 */
export const updateRescueTeam = (
    id: number,
    rescueTeamUpdate: RescueTeamUpdate,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<RescueTeam>(
      {url: `/rescue-teams/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: rescueTeamUpdate
    },
      options);
    }
  


export const getUpdateRescueTeamMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRescueTeam>>, TError,{id: number;data: RescueTeamUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateRescueTeam>>, TError,{id: number;data: RescueTeamUpdate}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateRescueTeam>>, {id: number;data: RescueTeamUpdate}> = (props) => {
          const {id,data} = props ?? {};

          return  updateRescueTeam(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateRescueTeamMutationResult = NonNullable<Awaited<ReturnType<typeof updateRescueTeam>>>
    export type UpdateRescueTeamMutationBody = RescueTeamUpdate
    export type UpdateRescueTeamMutationError = unknown

    /**
 * @summary Update rescue team
 */
export const useUpdateRescueTeam = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRescueTeam>>, TError,{id: number;data: RescueTeamUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof updateRescueTeam>>,
        TError,
        {id: number;data: RescueTeamUpdate},
        TContext
      > => {

      const mutationOptions = getUpdateRescueTeamMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Dijkstra shortest rescue route from team to incident
 */
export const planRescueRoute = (
    routePlanRequest: RoutePlanRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<RoutePlanResult>(
      {url: `/routes/plan`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: routePlanRequest
    },
      options);
    }
  


export const getPlanRescueRouteMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof planRescueRoute>>, TError,{data: RoutePlanRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof planRescueRoute>>, TError,{data: RoutePlanRequest}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof planRescueRoute>>, {data: RoutePlanRequest}> = (props) => {
          const {data} = props ?? {};

          return  planRescueRoute(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PlanRescueRouteMutationResult = NonNullable<Awaited<ReturnType<typeof planRescueRoute>>>
    export type PlanRescueRouteMutationBody = RoutePlanRequest
    export type PlanRescueRouteMutationError = unknown

    /**
 * @summary Dijkstra shortest rescue route from team to incident
 */
export const usePlanRescueRoute = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof planRescueRoute>>, TError,{data: RoutePlanRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof planRescueRoute>>,
        TError,
        {data: RoutePlanRequest},
        TContext
      > => {

      const mutationOptions = getPlanRescueRouteMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary List all saved rescue routes
 */
export const listRoutes = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RescueRoute[]>(
      {url: `/routes`, method: 'GET', signal
    },
      options);
    }
  

export const getListRoutesQueryKey = () => {
    return [`/routes`] as const;
    }

    
export const getListRoutesQueryOptions = <TData = Awaited<ReturnType<typeof listRoutes>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRoutes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListRoutesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listRoutes>>> = ({ signal }) => listRoutes(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listRoutes>>, TError, TData> & { queryKey: QueryKey }
}

export type ListRoutesQueryResult = NonNullable<Awaited<ReturnType<typeof listRoutes>>>
export type ListRoutesQueryError = unknown

/**
 * @summary List all saved rescue routes
 */
export const useListRoutes = <TData = Awaited<ReturnType<typeof listRoutes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRoutes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getListRoutesQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Analyze disaster image with AI
 */
export const analyzeDisasterImage = (
    imageAnalysisRequest: ImageAnalysisRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<ImageAnalysisResult>(
      {url: `/ai/analyze-image`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: imageAnalysisRequest
    },
      options);
    }
  


export const getAnalyzeDisasterImageMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof analyzeDisasterImage>>, TError,{data: ImageAnalysisRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof analyzeDisasterImage>>, TError,{data: ImageAnalysisRequest}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof analyzeDisasterImage>>, {data: ImageAnalysisRequest}> = (props) => {
          const {data} = props ?? {};

          return  analyzeDisasterImage(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AnalyzeDisasterImageMutationResult = NonNullable<Awaited<ReturnType<typeof analyzeDisasterImage>>>
    export type AnalyzeDisasterImageMutationBody = ImageAnalysisRequest
    export type AnalyzeDisasterImageMutationError = unknown

    /**
 * @summary Analyze disaster image with AI
 */
export const useAnalyzeDisasterImage = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof analyzeDisasterImage>>, TError,{data: ImageAnalysisRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof analyzeDisasterImage>>,
        TError,
        {data: ImageAnalysisRequest},
        TContext
      > => {

      const mutationOptions = getAnalyzeDisasterImageMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary AI-generated action plan for an incident
 */
export const getAiActionPlan = (
    actionPlanRequest: ActionPlanRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<ActionPlan>(
      {url: `/ai/recommend-action`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: actionPlanRequest
    },
      options);
    }
  


export const getGetAiActionPlanMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getAiActionPlan>>, TError,{data: ActionPlanRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getAiActionPlan>>, TError,{data: ActionPlanRequest}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getAiActionPlan>>, {data: ActionPlanRequest}> = (props) => {
          const {data} = props ?? {};

          return  getAiActionPlan(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type GetAiActionPlanMutationResult = NonNullable<Awaited<ReturnType<typeof getAiActionPlan>>>
    export type GetAiActionPlanMutationBody = ActionPlanRequest
    export type GetAiActionPlanMutationError = unknown

    /**
 * @summary AI-generated action plan for an incident
 */
export const useGetAiActionPlan = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getAiActionPlan>>, TError,{data: ActionPlanRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof getAiActionPlan>>,
        TError,
        {data: ActionPlanRequest},
        TContext
      > => {

      const mutationOptions = getGetAiActionPlanMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary List recent AI predictions
 */
export const listAiPredictions = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AiPrediction[]>(
      {url: `/ai/predictions`, method: 'GET', signal
    },
      options);
    }
  

export const getListAiPredictionsQueryKey = () => {
    return [`/ai/predictions`] as const;
    }

    
export const getListAiPredictionsQueryOptions = <TData = Awaited<ReturnType<typeof listAiPredictions>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAiPredictions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAiPredictionsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAiPredictions>>> = ({ signal }) => listAiPredictions(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAiPredictions>>, TError, TData> & { queryKey: QueryKey }
}

export type ListAiPredictionsQueryResult = NonNullable<Awaited<ReturnType<typeof listAiPredictions>>>
export type ListAiPredictionsQueryError = unknown

/**
 * @summary List recent AI predictions
 */
export const useListAiPredictions = <TData = Awaited<ReturnType<typeof listAiPredictions>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAiPredictions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getListAiPredictionsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Population impact by region
 */
export const getRegionImpact = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RegionImpact[]>(
      {url: `/analytics/region-impact`, method: 'GET', signal
    },
      options);
    }
  

export const getGetRegionImpactQueryKey = () => {
    return [`/analytics/region-impact`] as const;
    }

    
export const getGetRegionImpactQueryOptions = <TData = Awaited<ReturnType<typeof getRegionImpact>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRegionImpact>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRegionImpactQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRegionImpact>>> = ({ signal }) => getRegionImpact(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRegionImpact>>, TError, TData> & { queryKey: QueryKey }
}

export type GetRegionImpactQueryResult = NonNullable<Awaited<ReturnType<typeof getRegionImpact>>>
export type GetRegionImpactQueryError = unknown

/**
 * @summary Population impact by region
 */
export const useGetRegionImpact = <TData = Awaited<ReturnType<typeof getRegionImpact>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRegionImpact>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetRegionImpactQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Rescue operation efficiency metrics
 */
export const getRescueEfficiency = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RescueEfficiency>(
      {url: `/analytics/rescue-efficiency`, method: 'GET', signal
    },
      options);
    }
  

export const getGetRescueEfficiencyQueryKey = () => {
    return [`/analytics/rescue-efficiency`] as const;
    }

    
export const getGetRescueEfficiencyQueryOptions = <TData = Awaited<ReturnType<typeof getRescueEfficiency>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRescueEfficiency>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRescueEfficiencyQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRescueEfficiency>>> = ({ signal }) => getRescueEfficiency(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRescueEfficiency>>, TError, TData> & { queryKey: QueryKey }
}

export type GetRescueEfficiencyQueryResult = NonNullable<Awaited<ReturnType<typeof getRescueEfficiency>>>
export type GetRescueEfficiencyQueryError = unknown

/**
 * @summary Rescue operation efficiency metrics
 */
export const useGetRescueEfficiency = <TData = Awaited<ReturnType<typeof getRescueEfficiency>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRescueEfficiency>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetRescueEfficiencyQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Recent emergency ticker events
 */
export const getLiveTicker = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<TickerEvent[]>(
      {url: `/analytics/live-ticker`, method: 'GET', signal
    },
      options);
    }
  

export const getGetLiveTickerQueryKey = () => {
    return [`/analytics/live-ticker`] as const;
    }

    
export const getGetLiveTickerQueryOptions = <TData = Awaited<ReturnType<typeof getLiveTicker>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiveTicker>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLiveTickerQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLiveTicker>>> = ({ signal }) => getLiveTicker(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLiveTicker>>, TError, TData> & { queryKey: QueryKey }
}

export type GetLiveTickerQueryResult = NonNullable<Awaited<ReturnType<typeof getLiveTicker>>>
export type GetLiveTickerQueryError = unknown

/**
 * @summary Recent emergency ticker events
 */
export const useGetLiveTicker = <TData = Awaited<ReturnType<typeof getLiveTicker>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiveTicker>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetLiveTickerQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}






export const getHealthCheckResponseMock = (overrideResponse: Partial< HealthStatus > = {}): HealthStatus => ({status: faker.word.sample(), ...overrideResponse})

export const getListIncidentsResponseMock = (): Incident[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({affectedPopulation: faker.number.int({min: 0, max: undefined}), category: faker.helpers.arrayElement(['flood','earthquake','cyclone','fire','landslide'] as const), createdAt: faker.word.sample(), description: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined]), id: faker.number.int({min: undefined, max: undefined}), imageUrl: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined]), latitude: faker.number.int({min: -90, max: 90}), longitude: faker.number.int({min: -180, max: 180}), region: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined]), severity: faker.number.int({min: 1, max: 10}), status: faker.helpers.arrayElement(['active','resolved','monitoring','critical'] as const), title: faker.word.sample(), updatedAt: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined])})))

export const getCreateIncidentResponseMock = (overrideResponse: Partial< Incident > = {}): Incident => ({affectedPopulation: faker.number.int({min: 0, max: undefined}), category: faker.helpers.arrayElement(['flood','earthquake','cyclone','fire','landslide'] as const), createdAt: faker.word.sample(), description: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined]), id: faker.number.int({min: undefined, max: undefined}), imageUrl: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined]), latitude: faker.number.int({min: -90, max: 90}), longitude: faker.number.int({min: -180, max: 180}), region: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined]), severity: faker.number.int({min: 1, max: 10}), status: faker.helpers.arrayElement(['active','resolved','monitoring','critical'] as const), title: faker.word.sample(), updatedAt: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined]), ...overrideResponse})

export const getGetIncidentResponseMock = (overrideResponse: Partial< Incident > = {}): Incident => ({affectedPopulation: faker.number.int({min: 0, max: undefined}), category: faker.helpers.arrayElement(['flood','earthquake','cyclone','fire','landslide'] as const), createdAt: faker.word.sample(), description: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined]), id: faker.number.int({min: undefined, max: undefined}), imageUrl: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined]), latitude: faker.number.int({min: -90, max: 90}), longitude: faker.number.int({min: -180, max: 180}), region: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined]), severity: faker.number.int({min: 1, max: 10}), status: faker.helpers.arrayElement(['active','resolved','monitoring','critical'] as const), title: faker.word.sample(), updatedAt: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined]), ...overrideResponse})

export const getUpdateIncidentResponseMock = (overrideResponse: Partial< Incident > = {}): Incident => ({affectedPopulation: faker.number.int({min: 0, max: undefined}), category: faker.helpers.arrayElement(['flood','earthquake','cyclone','fire','landslide'] as const), createdAt: faker.word.sample(), description: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined]), id: faker.number.int({min: undefined, max: undefined}), imageUrl: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined]), latitude: faker.number.int({min: -90, max: 90}), longitude: faker.number.int({min: -180, max: 180}), region: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined]), severity: faker.number.int({min: 1, max: 10}), status: faker.helpers.arrayElement(['active','resolved','monitoring','critical'] as const), title: faker.word.sample(), updatedAt: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined]), ...overrideResponse})

export const getGetIncidentSummaryResponseMock = (overrideResponse: Partial< IncidentSummary > = {}): IncidentSummary => ({activeRescueOps: faker.number.int({min: undefined, max: undefined}), criticalIncidents: faker.number.int({min: undefined, max: undefined}), populationAffected: faker.number.int({min: undefined, max: undefined}), resourceUtilizationPct: faker.number.int({min: undefined, max: undefined}), shelterOccupancy: faker.number.int({min: undefined, max: undefined}), totalIncidents: faker.number.int({min: undefined, max: undefined}), ...overrideResponse})

export const getGetIncidentTrendsResponseMock = (): TrendPoint[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({count: faker.number.int({min: undefined, max: undefined}), date: faker.word.sample(), severity: faker.number.int({min: 1, max: 10})})))

export const getGetIncidentsByCategoryResponseMock = (): CategoryCount[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({category: faker.word.sample(), count: faker.number.int({min: undefined, max: undefined}), populationAffected: faker.number.int({min: undefined, max: undefined})})))

export const getListResourcesResponseMock = (): Resource[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({availableQuantity: faker.number.int({min: undefined, max: undefined}), category: faker.helpers.arrayElement(['food','water','medical','rescue_team','boat','ambulance'] as const), id: faker.number.int({min: undefined, max: undefined}), latitude: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}),null]), undefined]), location: faker.word.sample(), longitude: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}),null]), undefined]), name: faker.word.sample(), totalQuantity: faker.number.int({min: undefined, max: undefined}), unit: faker.word.sample()})))

export const getCreateResourceResponseMock = (overrideResponse: Partial< Resource > = {}): Resource => ({availableQuantity: faker.number.int({min: undefined, max: undefined}), category: faker.helpers.arrayElement(['food','water','medical','rescue_team','boat','ambulance'] as const), id: faker.number.int({min: undefined, max: undefined}), latitude: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}),null]), undefined]), location: faker.word.sample(), longitude: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}),null]), undefined]), name: faker.word.sample(), totalQuantity: faker.number.int({min: undefined, max: undefined}), unit: faker.word.sample(), ...overrideResponse})

export const getUpdateResourceResponseMock = (overrideResponse: Partial< Resource > = {}): Resource => ({availableQuantity: faker.number.int({min: undefined, max: undefined}), category: faker.helpers.arrayElement(['food','water','medical','rescue_team','boat','ambulance'] as const), id: faker.number.int({min: undefined, max: undefined}), latitude: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}),null]), undefined]), location: faker.word.sample(), longitude: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}),null]), undefined]), name: faker.word.sample(), totalQuantity: faker.number.int({min: undefined, max: undefined}), unit: faker.word.sample(), ...overrideResponse})

export const getAllocateResourcesResponseMock = (overrideResponse: Partial< AllocationResult > = {}): AllocationResult => ({allocations: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({allocated: faker.number.int({min: undefined, max: undefined}), category: faker.word.sample(), resourceId: faker.number.int({min: undefined, max: undefined}), resourceName: faker.word.sample(), unit: faker.word.sample()})), efficiencyScore: faker.number.int({min: undefined, max: undefined}), incidentId: faker.number.int({min: undefined, max: undefined}), shortages: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), ...overrideResponse})

export const getGetResourceUtilizationResponseMock = (): ResourceUtilization[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({available: faker.number.int({min: undefined, max: undefined}), category: faker.word.sample(), total: faker.number.int({min: undefined, max: undefined}), used: faker.number.int({min: undefined, max: undefined}), utilizationPct: faker.number.int({min: undefined, max: undefined})})))

export const getListSheltersResponseMock = (): Shelter[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({address: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined]), capacity: faker.number.int({min: 0, max: undefined}), currentOccupancy: faker.number.int({min: undefined, max: undefined}), facilities: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), undefined]), id: faker.number.int({min: undefined, max: undefined}), latitude: faker.number.int({min: -90, max: 90}), longitude: faker.number.int({min: -180, max: 180}), name: faker.word.sample(), status: faker.helpers.arrayElement(['available','full','closed'] as const)})))

export const getCreateShelterResponseMock = (overrideResponse: Partial< Shelter > = {}): Shelter => ({address: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined]), capacity: faker.number.int({min: 0, max: undefined}), currentOccupancy: faker.number.int({min: undefined, max: undefined}), facilities: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), undefined]), id: faker.number.int({min: undefined, max: undefined}), latitude: faker.number.int({min: -90, max: 90}), longitude: faker.number.int({min: -180, max: 180}), name: faker.word.sample(), status: faker.helpers.arrayElement(['available','full','closed'] as const), ...overrideResponse})

export const getUpdateShelterResponseMock = (overrideResponse: Partial< Shelter > = {}): Shelter => ({address: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined]), capacity: faker.number.int({min: 0, max: undefined}), currentOccupancy: faker.number.int({min: undefined, max: undefined}), facilities: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), undefined]), id: faker.number.int({min: undefined, max: undefined}), latitude: faker.number.int({min: -90, max: 90}), longitude: faker.number.int({min: -180, max: 180}), name: faker.word.sample(), status: faker.helpers.arrayElement(['available','full','closed'] as const), ...overrideResponse})

export const getRecommendSheltersResponseMock = (): ShelterRecommendation[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({availableCapacity: faker.number.int({min: 0, max: undefined}), distanceKm: faker.number.int({min: undefined, max: undefined}), estimatedTravelMinutes: faker.number.int({min: undefined, max: undefined}), score: faker.number.int({min: undefined, max: undefined}), shelter: {address: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.word.sample(),null]), undefined]), capacity: faker.number.int({min: 0, max: undefined}), currentOccupancy: faker.number.int({min: undefined, max: undefined}), facilities: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), undefined]), id: faker.number.int({min: undefined, max: undefined}), latitude: faker.number.int({min: -90, max: 90}), longitude: faker.number.int({min: -180, max: 180}), name: faker.word.sample(), status: faker.helpers.arrayElement(['available','full','closed'] as const)}})))

export const getListRescueTeamsResponseMock = (): RescueTeam[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({assignedIncidentId: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}),null]), undefined]), equipment: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), undefined]), id: faker.number.int({min: undefined, max: undefined}), latitude: faker.number.int({min: -90, max: 90}), longitude: faker.number.int({min: -180, max: 180}), name: faker.word.sample(), size: faker.number.int({min: 1, max: undefined}), status: faker.helpers.arrayElement(['available','deployed','resting','standby'] as const), type: faker.helpers.arrayElement(['medical','firefighting','flood_rescue','search_rescue','logistics'] as const)})))

export const getCreateRescueTeamResponseMock = (overrideResponse: Partial< RescueTeam > = {}): RescueTeam => ({assignedIncidentId: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}),null]), undefined]), equipment: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), undefined]), id: faker.number.int({min: undefined, max: undefined}), latitude: faker.number.int({min: -90, max: 90}), longitude: faker.number.int({min: -180, max: 180}), name: faker.word.sample(), size: faker.number.int({min: 1, max: undefined}), status: faker.helpers.arrayElement(['available','deployed','resting','standby'] as const), type: faker.helpers.arrayElement(['medical','firefighting','flood_rescue','search_rescue','logistics'] as const), ...overrideResponse})

export const getUpdateRescueTeamResponseMock = (overrideResponse: Partial< RescueTeam > = {}): RescueTeam => ({assignedIncidentId: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}),null]), undefined]), equipment: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), undefined]), id: faker.number.int({min: undefined, max: undefined}), latitude: faker.number.int({min: -90, max: 90}), longitude: faker.number.int({min: -180, max: 180}), name: faker.word.sample(), size: faker.number.int({min: 1, max: undefined}), status: faker.helpers.arrayElement(['available','deployed','resting','standby'] as const), type: faker.helpers.arrayElement(['medical','firefighting','flood_rescue','search_rescue','logistics'] as const), ...overrideResponse})

export const getPlanRescueRouteResponseMock = (overrideResponse: Partial< RoutePlanResult > = {}): RoutePlanResult => ({estimatedMinutes: faker.number.int({min: undefined, max: undefined}), routeId: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}),null]), undefined]), safetyScore: faker.number.int({min: undefined, max: undefined}), totalDistanceKm: faker.number.int({min: undefined, max: undefined}), waypoints: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({label: faker.word.sample(), latitude: faker.number.int({min: -90, max: 90}), longitude: faker.number.int({min: -180, max: 180}), order: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined])})), ...overrideResponse})

export const getListRoutesResponseMock = (): RescueRoute[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({createdAt: faker.word.sample(), estimatedMinutes: faker.number.int({min: undefined, max: undefined}), id: faker.number.int({min: undefined, max: undefined}), incidentId: faker.number.int({min: undefined, max: undefined}), safetyScore: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), status: faker.helpers.arrayElement(['planned','active','completed'] as const), teamId: faker.number.int({min: undefined, max: undefined}), totalDistanceKm: faker.number.int({min: undefined, max: undefined})})))

export const getAnalyzeDisasterImageResponseMock = (overrideResponse: Partial< ImageAnalysisResult > = {}): ImageAnalysisResult => ({analysisNotes: faker.word.sample(), confidenceScore: faker.number.int({min: undefined, max: undefined}), damageLevel: faker.helpers.arrayElement(['minimal','moderate','severe','catastrophic'] as const), detectedCategory: faker.helpers.arrayElement(['flood','earthquake','cyclone','fire','landslide','unknown'] as const), estimatedCasualties: faker.number.int({min: undefined, max: undefined}), requiredResources: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), severity: faker.number.int({min: 1, max: 10}), suggestedPriority: faker.helpers.arrayElement(['low','medium','high','critical'] as const), ...overrideResponse})

export const getGetAiActionPlanResponseMock = (overrideResponse: Partial< ActionPlan > = {}): ActionPlan => ({aiNotes: faker.word.sample(), estimatedResponseHours: faker.number.int({min: undefined, max: undefined}), evacuationUrgency: faker.helpers.arrayElement(['low','moderate','high','immediate'] as const), incidentId: faker.number.int({min: undefined, max: undefined}), requiredTeams: faker.number.int({min: undefined, max: undefined}), resourcePlan: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({allocated: faker.number.int({min: undefined, max: undefined}), category: faker.word.sample(), resourceId: faker.number.int({min: undefined, max: undefined}), resourceName: faker.word.sample(), unit: faker.word.sample()})), shelterCapacityNeeded: faker.number.int({min: undefined, max: undefined}), ...overrideResponse})

export const getListAiPredictionsResponseMock = (): AiPrediction[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({confidenceScore: faker.number.int({min: undefined, max: undefined}), createdAt: faker.word.sample(), id: faker.number.int({min: undefined, max: undefined}), incidentId: faker.number.int({min: undefined, max: undefined}), result: faker.word.sample(), type: faker.helpers.arrayElement(['image_analysis','action_plan','severity_prediction'] as const)})))

export const getGetRegionImpactResponseMock = (): RegionImpact[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({avgSeverity: faker.number.int({min: undefined, max: undefined}), incidentCount: faker.number.int({min: undefined, max: undefined}), latitude: faker.number.int({min: -90, max: 90}), longitude: faker.number.int({min: -180, max: 180}), region: faker.word.sample(), totalAffected: faker.number.int({min: undefined, max: undefined})})))

export const getGetRescueEfficiencyResponseMock = (overrideResponse: Partial< RescueEfficiency > = {}): RescueEfficiency => ({avgCoverageKm: faker.number.int({min: undefined, max: undefined}), avgResponseMinutes: faker.number.int({min: undefined, max: undefined}), incidentsResolved: faker.number.int({min: undefined, max: undefined}), successRate: faker.number.int({min: undefined, max: undefined}), teamsDeployed: faker.number.int({min: undefined, max: undefined}), ...overrideResponse})

export const getGetLiveTickerResponseMock = (): TickerEvent[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({category: faker.word.sample(), id: faker.number.int({min: undefined, max: undefined}), message: faker.word.sample(), region: faker.word.sample(), severity: faker.number.int({min: 1, max: 10}), timestamp: faker.word.sample()})))


export const getHealthCheckMockHandler = (overrideResponse?: HealthStatus | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<HealthStatus> | HealthStatus)) => {
  return http.get('*/healthz', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getHealthCheckResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getListIncidentsMockHandler = (overrideResponse?: Incident[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Incident[]> | Incident[])) => {
  return http.get('*/incidents', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getListIncidentsResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getCreateIncidentMockHandler = (overrideResponse?: Incident | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Incident> | Incident)) => {
  return http.post('*/incidents', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getCreateIncidentResponseMock()),
      {
        status: 201,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetIncidentMockHandler = (overrideResponse?: Incident | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Incident> | Incident)) => {
  return http.get('*/incidents/:id', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetIncidentResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getUpdateIncidentMockHandler = (overrideResponse?: Incident | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<Incident> | Incident)) => {
  return http.patch('*/incidents/:id', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getUpdateIncidentResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getDeleteIncidentMockHandler = () => {
  return http.delete('*/incidents/:id', async () => {await delay(1000);
    return new HttpResponse(null,
      {
        status: 204,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetIncidentSummaryMockHandler = (overrideResponse?: IncidentSummary | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<IncidentSummary> | IncidentSummary)) => {
  return http.get('*/incidents/stats/summary', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetIncidentSummaryResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetIncidentTrendsMockHandler = (overrideResponse?: TrendPoint[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<TrendPoint[]> | TrendPoint[])) => {
  return http.get('*/incidents/stats/trends', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetIncidentTrendsResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetIncidentsByCategoryMockHandler = (overrideResponse?: CategoryCount[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<CategoryCount[]> | CategoryCount[])) => {
  return http.get('*/incidents/stats/by-category', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetIncidentsByCategoryResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getListResourcesMockHandler = (overrideResponse?: Resource[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Resource[]> | Resource[])) => {
  return http.get('*/resources', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getListResourcesResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getCreateResourceMockHandler = (overrideResponse?: Resource | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Resource> | Resource)) => {
  return http.post('*/resources', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getCreateResourceResponseMock()),
      {
        status: 201,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getUpdateResourceMockHandler = (overrideResponse?: Resource | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<Resource> | Resource)) => {
  return http.patch('*/resources/:id', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getUpdateResourceResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getAllocateResourcesMockHandler = (overrideResponse?: AllocationResult | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<AllocationResult> | AllocationResult)) => {
  return http.post('*/resources/allocate', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getAllocateResourcesResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetResourceUtilizationMockHandler = (overrideResponse?: ResourceUtilization[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ResourceUtilization[]> | ResourceUtilization[])) => {
  return http.get('*/resources/stats/utilization', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetResourceUtilizationResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getListSheltersMockHandler = (overrideResponse?: Shelter[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Shelter[]> | Shelter[])) => {
  return http.get('*/shelters', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getListSheltersResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getCreateShelterMockHandler = (overrideResponse?: Shelter | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Shelter> | Shelter)) => {
  return http.post('*/shelters', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getCreateShelterResponseMock()),
      {
        status: 201,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getUpdateShelterMockHandler = (overrideResponse?: Shelter | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<Shelter> | Shelter)) => {
  return http.patch('*/shelters/:id', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getUpdateShelterResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getDeleteShelterMockHandler = () => {
  return http.delete('*/shelters/:id', async () => {await delay(1000);
    return new HttpResponse(null,
      {
        status: 204,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getRecommendSheltersMockHandler = (overrideResponse?: ShelterRecommendation[] | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ShelterRecommendation[]> | ShelterRecommendation[])) => {
  return http.post('*/shelters/recommend', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getRecommendSheltersResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getListRescueTeamsMockHandler = (overrideResponse?: RescueTeam[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<RescueTeam[]> | RescueTeam[])) => {
  return http.get('*/rescue-teams', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getListRescueTeamsResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getCreateRescueTeamMockHandler = (overrideResponse?: RescueTeam | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<RescueTeam> | RescueTeam)) => {
  return http.post('*/rescue-teams', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getCreateRescueTeamResponseMock()),
      {
        status: 201,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getUpdateRescueTeamMockHandler = (overrideResponse?: RescueTeam | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<RescueTeam> | RescueTeam)) => {
  return http.patch('*/rescue-teams/:id', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getUpdateRescueTeamResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getPlanRescueRouteMockHandler = (overrideResponse?: RoutePlanResult | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<RoutePlanResult> | RoutePlanResult)) => {
  return http.post('*/routes/plan', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getPlanRescueRouteResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getListRoutesMockHandler = (overrideResponse?: RescueRoute[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<RescueRoute[]> | RescueRoute[])) => {
  return http.get('*/routes', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getListRoutesResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getAnalyzeDisasterImageMockHandler = (overrideResponse?: ImageAnalysisResult | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ImageAnalysisResult> | ImageAnalysisResult)) => {
  return http.post('*/ai/analyze-image', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getAnalyzeDisasterImageResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetAiActionPlanMockHandler = (overrideResponse?: ActionPlan | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ActionPlan> | ActionPlan)) => {
  return http.post('*/ai/recommend-action', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetAiActionPlanResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getListAiPredictionsMockHandler = (overrideResponse?: AiPrediction[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<AiPrediction[]> | AiPrediction[])) => {
  return http.get('*/ai/predictions', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getListAiPredictionsResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetRegionImpactMockHandler = (overrideResponse?: RegionImpact[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<RegionImpact[]> | RegionImpact[])) => {
  return http.get('*/analytics/region-impact', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetRegionImpactResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetRescueEfficiencyMockHandler = (overrideResponse?: RescueEfficiency | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<RescueEfficiency> | RescueEfficiency)) => {
  return http.get('*/analytics/rescue-efficiency', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetRescueEfficiencyResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetLiveTickerMockHandler = (overrideResponse?: TickerEvent[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<TickerEvent[]> | TickerEvent[])) => {
  return http.get('*/analytics/live-ticker', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetLiveTickerResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}
export const getApiMock = () => [
  getHealthCheckMockHandler(),
  getListIncidentsMockHandler(),
  getCreateIncidentMockHandler(),
  getGetIncidentMockHandler(),
  getUpdateIncidentMockHandler(),
  getDeleteIncidentMockHandler(),
  getGetIncidentSummaryMockHandler(),
  getGetIncidentTrendsMockHandler(),
  getGetIncidentsByCategoryMockHandler(),
  getListResourcesMockHandler(),
  getCreateResourceMockHandler(),
  getUpdateResourceMockHandler(),
  getAllocateResourcesMockHandler(),
  getGetResourceUtilizationMockHandler(),
  getListSheltersMockHandler(),
  getCreateShelterMockHandler(),
  getUpdateShelterMockHandler(),
  getDeleteShelterMockHandler(),
  getRecommendSheltersMockHandler(),
  getListRescueTeamsMockHandler(),
  getCreateRescueTeamMockHandler(),
  getUpdateRescueTeamMockHandler(),
  getPlanRescueRouteMockHandler(),
  getListRoutesMockHandler(),
  getAnalyzeDisasterImageMockHandler(),
  getGetAiActionPlanMockHandler(),
  getListAiPredictionsMockHandler(),
  getGetRegionImpactMockHandler(),
  getGetRescueEfficiencyMockHandler(),
  getGetLiveTickerMockHandler()
]
