/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Api
 * Smart Disaster Response and Resource Allocation Platform API
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query'
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import axios from 'axios'
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  RegionImpact,
  RescueEfficiency,
  TickerEvent
} from '../../../api-zod/src/generated'

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;



/**
 * @summary Population impact by region
 */
export const getRegionImpact = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RegionImpact[]>> => {
    
    return axios.get(
      `/analytics/region-impact`,options
    );
  }


export const getGetRegionImpactQueryKey = () => {
    return [`/analytics/region-impact`] as const;
    }

    
export const getGetRegionImpactQueryOptions = <TData = Awaited<ReturnType<typeof getRegionImpact>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRegionImpact>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRegionImpactQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRegionImpact>>> = ({ signal }) => getRegionImpact({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRegionImpact>>, TError, TData> & { queryKey: QueryKey }
}

export type GetRegionImpactQueryResult = NonNullable<Awaited<ReturnType<typeof getRegionImpact>>>
export type GetRegionImpactQueryError = AxiosError<unknown>

/**
 * @summary Population impact by region
 */
export const useGetRegionImpact = <TData = Awaited<ReturnType<typeof getRegionImpact>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRegionImpact>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetRegionImpactQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Rescue operation efficiency metrics
 */
export const getRescueEfficiency = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RescueEfficiency>> => {
    
    return axios.get(
      `/analytics/rescue-efficiency`,options
    );
  }


export const getGetRescueEfficiencyQueryKey = () => {
    return [`/analytics/rescue-efficiency`] as const;
    }

    
export const getGetRescueEfficiencyQueryOptions = <TData = Awaited<ReturnType<typeof getRescueEfficiency>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRescueEfficiency>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRescueEfficiencyQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRescueEfficiency>>> = ({ signal }) => getRescueEfficiency({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRescueEfficiency>>, TError, TData> & { queryKey: QueryKey }
}

export type GetRescueEfficiencyQueryResult = NonNullable<Awaited<ReturnType<typeof getRescueEfficiency>>>
export type GetRescueEfficiencyQueryError = AxiosError<unknown>

/**
 * @summary Rescue operation efficiency metrics
 */
export const useGetRescueEfficiency = <TData = Awaited<ReturnType<typeof getRescueEfficiency>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRescueEfficiency>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetRescueEfficiencyQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Recent emergency ticker events
 */
export const getLiveTicker = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TickerEvent[]>> => {
    
    return axios.get(
      `/analytics/live-ticker`,options
    );
  }


export const getGetLiveTickerQueryKey = () => {
    return [`/analytics/live-ticker`] as const;
    }

    
export const getGetLiveTickerQueryOptions = <TData = Awaited<ReturnType<typeof getLiveTicker>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiveTicker>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLiveTickerQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLiveTicker>>> = ({ signal }) => getLiveTicker({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLiveTicker>>, TError, TData> & { queryKey: QueryKey }
}

export type GetLiveTickerQueryResult = NonNullable<Awaited<ReturnType<typeof getLiveTicker>>>
export type GetLiveTickerQueryError = AxiosError<unknown>

/**
 * @summary Recent emergency ticker events
 */
export const useGetLiveTicker = <TData = Awaited<ReturnType<typeof getLiveTicker>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiveTicker>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetLiveTickerQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



