/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Api
 * Smart Disaster Response and Resource Allocation Platform API
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker'
import {
  HttpResponse,
  delay,
  http
} from 'msw'
import type {
  RegionImpact,
  RescueEfficiency,
  TickerEvent
} from '../../../api-zod/src/generated'

export const getGetRegionImpactResponseMock = (): RegionImpact[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({avgSeverity: faker.number.int({min: undefined, max: undefined}), incidentCount: faker.number.int({min: undefined, max: undefined}), latitude: faker.number.int({min: undefined, max: undefined}), longitude: faker.number.int({min: undefined, max: undefined}), region: faker.word.sample(), totalAffected: faker.number.int({min: undefined, max: undefined})})))

export const getGetRescueEfficiencyResponseMock = (overrideResponse: Partial< RescueEfficiency > = {}): RescueEfficiency => ({avgCoverageKm: faker.number.int({min: undefined, max: undefined}), avgResponseMinutes: faker.number.int({min: undefined, max: undefined}), incidentsResolved: faker.number.int({min: undefined, max: undefined}), successRate: faker.number.int({min: undefined, max: undefined}), teamsDeployed: faker.number.int({min: undefined, max: undefined}), ...overrideResponse})

export const getGetLiveTickerResponseMock = (): TickerEvent[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({category: faker.word.sample(), id: faker.number.int({min: undefined, max: undefined}), message: faker.word.sample(), region: faker.word.sample(), severity: faker.number.int({min: undefined, max: undefined}), timestamp: faker.word.sample()})))


export const getGetRegionImpactMockHandler = (overrideResponse?: RegionImpact[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<RegionImpact[]> | RegionImpact[])) => {
  return http.get('*/analytics/region-impact', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetRegionImpactResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetRescueEfficiencyMockHandler = (overrideResponse?: RescueEfficiency | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<RescueEfficiency> | RescueEfficiency)) => {
  return http.get('*/analytics/rescue-efficiency', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetRescueEfficiencyResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetLiveTickerMockHandler = (overrideResponse?: TickerEvent[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<TickerEvent[]> | TickerEvent[])) => {
  return http.get('*/analytics/live-ticker', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetLiveTickerResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}
export const getAnalyticsMock = () => [
  getGetRegionImpactMockHandler(),
  getGetRescueEfficiencyMockHandler(),
  getGetLiveTickerMockHandler()
]
