/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Api
 * Smart Disaster Response and Resource Allocation Platform API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import axios from 'axios'
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  RescueTeam,
  RescueTeamInput,
  RescueTeamUpdate
} from '../../../api-zod/src/generated'

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;



/**
 * @summary List rescue teams
 */
export const listRescueTeams = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RescueTeam[]>> => {
    
    return axios.get(
      `/rescue-teams`,options
    );
  }


export const getListRescueTeamsQueryKey = () => {
    return [`/rescue-teams`] as const;
    }

    
export const getListRescueTeamsQueryOptions = <TData = Awaited<ReturnType<typeof listRescueTeams>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRescueTeams>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListRescueTeamsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listRescueTeams>>> = ({ signal }) => listRescueTeams({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listRescueTeams>>, TError, TData> & { queryKey: QueryKey }
}

export type ListRescueTeamsQueryResult = NonNullable<Awaited<ReturnType<typeof listRescueTeams>>>
export type ListRescueTeamsQueryError = AxiosError<unknown>

/**
 * @summary List rescue teams
 */
export const useListRescueTeams = <TData = Awaited<ReturnType<typeof listRescueTeams>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRescueTeams>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getListRescueTeamsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Register a rescue team
 */
export const createRescueTeam = (
    rescueTeamInput: RescueTeamInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RescueTeam>> => {
    
    return axios.post(
      `/rescue-teams`,
      rescueTeamInput,options
    );
  }



export const getCreateRescueTeamMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRescueTeam>>, TError,{data: RescueTeamInput}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createRescueTeam>>, TError,{data: RescueTeamInput}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createRescueTeam>>, {data: RescueTeamInput}> = (props) => {
          const {data} = props ?? {};

          return  createRescueTeam(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateRescueTeamMutationResult = NonNullable<Awaited<ReturnType<typeof createRescueTeam>>>
    export type CreateRescueTeamMutationBody = RescueTeamInput
    export type CreateRescueTeamMutationError = AxiosError<unknown>

    /**
 * @summary Register a rescue team
 */
export const useCreateRescueTeam = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRescueTeam>>, TError,{data: RescueTeamInput}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof createRescueTeam>>,
        TError,
        {data: RescueTeamInput},
        TContext
      > => {

      const mutationOptions = getCreateRescueTeamMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Update rescue team
 */
export const updateRescueTeam = (
    id: number,
    rescueTeamUpdate: RescueTeamUpdate, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RescueTeam>> => {
    
    return axios.patch(
      `/rescue-teams/${id}`,
      rescueTeamUpdate,options
    );
  }



export const getUpdateRescueTeamMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRescueTeam>>, TError,{id: number;data: RescueTeamUpdate}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateRescueTeam>>, TError,{id: number;data: RescueTeamUpdate}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateRescueTeam>>, {id: number;data: RescueTeamUpdate}> = (props) => {
          const {id,data} = props ?? {};

          return  updateRescueTeam(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateRescueTeamMutationResult = NonNullable<Awaited<ReturnType<typeof updateRescueTeam>>>
    export type UpdateRescueTeamMutationBody = RescueTeamUpdate
    export type UpdateRescueTeamMutationError = AxiosError<unknown>

    /**
 * @summary Update rescue team
 */
export const useUpdateRescueTeam = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRescueTeam>>, TError,{id: number;data: RescueTeamUpdate}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof updateRescueTeam>>,
        TError,
        {id: number;data: RescueTeamUpdate},
        TContext
      > => {

      const mutationOptions = getUpdateRescueTeamMutationOptions(options);

      return useMutation(mutationOptions);
    }
    