/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Api
 * Smart Disaster Response and Resource Allocation Platform API
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker'
import {
  HttpResponse,
  delay,
  http
} from 'msw'
import type {
  RescueTeam
} from '../../../api-zod/src/generated'

export const getListRescueTeamsResponseMock = (): RescueTeam[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({assignedIncidentId: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}),null]), undefined]), equipment: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), undefined]), id: faker.number.int({min: undefined, max: undefined}), latitude: faker.number.int({min: undefined, max: undefined}), longitude: faker.number.int({min: undefined, max: undefined}), name: faker.word.sample(), size: faker.number.int({min: undefined, max: undefined}), status: faker.helpers.arrayElement(['available','deployed','resting','standby'] as const), type: faker.helpers.arrayElement(['medical','firefighting','flood_rescue','search_rescue','logistics'] as const)})))

export const getCreateRescueTeamResponseMock = (overrideResponse: Partial< RescueTeam > = {}): RescueTeam => ({assignedIncidentId: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}),null]), undefined]), equipment: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), undefined]), id: faker.number.int({min: undefined, max: undefined}), latitude: faker.number.int({min: undefined, max: undefined}), longitude: faker.number.int({min: undefined, max: undefined}), name: faker.word.sample(), size: faker.number.int({min: undefined, max: undefined}), status: faker.helpers.arrayElement(['available','deployed','resting','standby'] as const), type: faker.helpers.arrayElement(['medical','firefighting','flood_rescue','search_rescue','logistics'] as const), ...overrideResponse})

export const getUpdateRescueTeamResponseMock = (overrideResponse: Partial< RescueTeam > = {}): RescueTeam => ({assignedIncidentId: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}),null]), undefined]), equipment: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), undefined]), id: faker.number.int({min: undefined, max: undefined}), latitude: faker.number.int({min: undefined, max: undefined}), longitude: faker.number.int({min: undefined, max: undefined}), name: faker.word.sample(), size: faker.number.int({min: undefined, max: undefined}), status: faker.helpers.arrayElement(['available','deployed','resting','standby'] as const), type: faker.helpers.arrayElement(['medical','firefighting','flood_rescue','search_rescue','logistics'] as const), ...overrideResponse})


export const getListRescueTeamsMockHandler = (overrideResponse?: RescueTeam[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<RescueTeam[]> | RescueTeam[])) => {
  return http.get('*/rescue-teams', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getListRescueTeamsResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getCreateRescueTeamMockHandler = (overrideResponse?: RescueTeam | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<RescueTeam> | RescueTeam)) => {
  return http.post('*/rescue-teams', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getCreateRescueTeamResponseMock()),
      {
        status: 201,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getUpdateRescueTeamMockHandler = (overrideResponse?: RescueTeam | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<RescueTeam> | RescueTeam)) => {
  return http.patch('*/rescue-teams/:id', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getUpdateRescueTeamResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}
export const getRescueTeamsMock = () => [
  getListRescueTeamsMockHandler(),
  getCreateRescueTeamMockHandler(),
  getUpdateRescueTeamMockHandler()
]
